export const data = [
  {
    "id": 181552,
    "link": "https://www.vilnius-events.lt/renginiai/digimarcon-at-home-2023-skaitmenines-rinkodaros-ziniasklaidos-ir-reklamos-konferencija/",
    "date": "2023-04-13 09:30",
    "all_dates": "",
    "title": "„DigiMarCon At Home 2023“",
    "content": "Išplėskite savo žinias šiomis temomis: paskyra pagrįsta rinkodara, elgsenos ir neuromarketingas, turinio rinkodara, pokalbių rinkodara, konversijų rodiklio optimizavimas, duomenų mokslas ir dideli duomenys, rinkodara el. paštu, geografinis taikymas ir artumo rinkodara, įsilaužimas į augimą, gaunama ir išeinanti rinkodara. , įtakingųjų rinkodara, mobilioji rinkodara, vietinė ir kontekstinė reklama, daugiakanalio rinkodara, mokamos paieškos rinkodara, personalizavimas ir privatumas.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/02/digimarcon-at-home-1.png",
    "event_url": "https://digimarconathome.com",
    "event_email": "",
    "location_name": "Organizatorių internetinėje svetainėje",
    "location_info": "",
    "category": "Kiti",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 180454,
    "link": "https://www.vilnius-events.lt/renginiai/leliu-spektaklis-maziesiems-1-5-m-apie-pasauli-5/",
    "date": "2023-04-13 10:00",
    "all_dates": "2023-04-13 10:00<br/>2023-04-30 11:00<br/>",
    "title": "Lėlių spektaklis mažiesiems (1-5 m. ) „Apie pasaulį“",
    "content": "BUSKITE, BUSKITE, BUSKITE,\r\nBUSKITE, ŽVĖRYS IR PAUKŠČIAI,\r\nBUSKITE, MEDŽIAI IR KRŪMAI,\r\nAUKITE, ŽOLĖS IR GĖLĖS, VAISIAI IR UOGOS.\r\nBUSKITE IR JŪS, ŽMONĖS, SAVO DVASIOJE IR ŠIRDYSE,\r\nBUSKITE, KAD AUGTUMĖTE.\r\n(A. Ilgevičienė „Pirminės šventės“)\r\n\r\nVaiko regos, klausos ir lytėjimo pojūčius lavinantis spektaklis aiškina pasaulį, kaip pilną kūrybos, nuolatinės kaitos ir judėjimo, besivadovaujantį gamtos ciklais, o žmogų, kaip gamtos dalį, kurioje telpa visa Visata.\r\nSpektaklis įkvėptas vieno seniausių mitų apie pasaulio sukūrimą. Mėnulyje ant vandens tupėjusi milžiniška antis. Padėjusi kiaušinį, ji ruošėsi perėti. Bet įsinorėjusi lesti, nuskridusi ieškoti maisto. Tuo tarpu užėjęs lietus, sudrėkinęs lizdą, jame pasidariusi skylė, pro ją kiaušinis iškritęs. Bekrisdamas atsimušęs į debesį ir perskilęs į tris dalis. Iš trynio atsiradusi žemė, iš baltymo – vandenys, iš kiauto – dangus su žvaigždėmis.\r\nScenarijaus autorė ir režisierė: Justina Jukonytė\r\nDailininkė: Neringa Keršulytė\r\nKompozitorius: Vykintas A. Jasaitis\r\n\r\nVaidina:\r\nErika GAIDAUSKAITĖ\r\nŠarūnas GEDVILAS\r\nDovilė KERŠYTĖ\r\nRaimondas KLEZYS\r\n\r\nPrieš spektaklį privaloma nusiauti avalynę. Galima avėti šlepetes.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/Apiepasauli.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus „Lėlės“ teatras",
    "location_info": "",
    "category": "Spektakliai, Vaikams",
    "location_address": "Arklių g. 5",
    "location_url": "http://www.teatraslele.lt"
  },
  {
    "id": 184750,
    "link": "https://www.vilnius-events.lt/renginiai/internetas-ir-jo-itaka-musu-smegenims/",
    "date": "2023-04-13 16:00",
    "all_dates": "",
    "title": "Internetas ir jo įtaka mūsų smegenims",
    "content": "„Senjorų pasaulis”  paskaitų ciklo „Balandžio polėkis” antroji atvira  paskaita  „Internetas ir jo įtaka mūsų smegenims” apie tai, kaip mūsų smegenims sekasi prisitaikyti prie šių dienų realybės – interneto. Aptarsime, kada interneto naudojimas tampa problema ir ką reiškia vis dažniau girdimas terminas “priklausomybė nuo interneto”, kaip perteklinis internetinių platformų naudojimas veikia mūsų smegenis ir kokių mažų žingsnelių galime imtis, kad patys netaptume probleminiais interneto naudotojais.\r\n\r\nVilniaus universiteto  Gyvybės mokslų centro Biomokslų instituto Neurobiologijos ir biofizikos katedros doktorantė Dovilė Šimkutė papasakos, kad realybė, atsiverianti už išmaniųjų įrenginių ekranų, iš tiesų gali keisti mūsų smegenis. Kaip tai vyksta?\r\n\r\n„Šiandienos gyvenimo norma – nuolat būti produktyviu ir užimtu, paliekant vis mažiau galimybių iš tiesų pailsėti. Žmonės nebegeba toleruoti nuobodulio. Stovime trijų asmenų eilėje ir jau traukiame iš kišenės telefoną. Dega raudonas šviesoforo signalas ir tai sunku išlaukti žalios, skubame patikrinti, ar niekas neatsiuntė žinutės, kas vyksta socialiniuose tinkluose“, – realistišką vaizdą prieš akis nupiešė Dovilė Šimkutė <a href=\"https://lsveikata.lt/lsveikata-lt-skaitomiausi/is-proto-varo-internetas-mokslininke-papasakojo-kaip-jis-veikia-smegenis-15402\">ČIA</a>\r\n\r\nTechnologijos, interneto sparta ir jo atveriamos veiklos bei galimybės kinta greičiau, nei mokslininkai spėja tirti jų poveikį žmogui. Be to, ši sritis yra pernelyg jauna, kad būtų galima tiksliai numatyti ilgalaikius skaitmenizacijos padarinius. Tačiau viena aišku – mūsų smegenys atsidūrė ne visai tokiame pasaulyje, kokiam vykstant evoliucijai ruošėsi ištisus tūkstantmečius. Kaip smegenys bando prisitaikyti prie joms staiga iškilusio skaitmeninio iššūkio, aiškinasi biomokslų atstovai.\r\n\r\nDažnas interneto naudojimas pats savaime nebūtinai yra problema. Problema jis tampa tada, kai asmuo nebesugeba kontroliuoti savo elgesio konkrečiose internetinėse platformose, nors ir patiria neigiamų padarinių svarbiose gyvenimo srityse.\r\n\r\n<strong>Registracija<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfp1-BXYF3T9GNNpkkDr5fZJDIH0TCxK9VjaGeKfX-Z15Qv2Q/viewform\"> čia</a></strong>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/simkute.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Online",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 184586,
    "link": "https://www.vilnius-events.lt/renginiai/paroda-atpazinti-tikruma-intuityvios-pojuciu-degustacijos/",
    "date": "2023-04-13 16:00",
    "all_dates": "2023-04-13 16:00<br/>2023-04-21 16:00<br/>2023-04-25 16:00<br/>",
    "title": "Paroda „Atpažinti tikrumą: intuityvios pojūčių degustacijos“",
    "content": "Intelektuali pramoga „Atpažinti tikrumą“ nagrinėja mūsų intuityvų santykį su nuolat besikeičiančia ir progresuojančia aplinka, kurioje skiriamoji linija tarp natūralių ir dirbtinų dalykų tampa beveik nematoma.\r\n\r\n„Amres Art Gallery“ erdvėse Jūsų lauks intuityvios pojūčių degustacijos, skatinančios pasitelkti visus penkis savo kūno pojūčius ir pamatyti, pajausti, paragauti, išgirsti, bei paliesti tikrus dalykus, atskirti juos nuo sintetinės prigimties elementų.\r\n\r\nŠiame pajautos žaidime „degustuosite“ viską: nuo maisto produktų iki augalų ir meno. Taip išmoksite atpažinti savo kūno siunčiamus signalus bei intuiciją, kurios svarba tampa vis akivaizdesnė šiame pokyčių ir neapibrėžties laikmetyje.\r\n_____________________\r\nDaugiau informacijos apie parodą ir bilietų įsigijimą <a href=\"https://www.gallery.amres.art/produktas/ekspozicijos/parodos/paroda-atpazinti-tikruma/\">ČIA  </a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/2_Paroda-apazinti-tikruma-2023-03-29-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "AMRES ART galerija",
    "location_info": "",
    "category": "Parodos, Ekskursijos",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 184843,
    "link": "https://www.vilnius-events.lt/renginiai/nacionalineje-bibliotekoje-diskusija-apie-valstybe/",
    "date": "2023-04-13 17:00",
    "all_dates": "",
    "title": "Nacionalinėje bibliotekoje – diskusija „Apie valstybę“",
    "content": "Lietuvos Respublikos Seimo Ateities komitetas kartu su Lietuvos nacionaline Martyno Mažvydo biblioteka kviečia į neformalaus Ateities forumo „Intelektualinis Lietuvos savarankiškumas“ diskusiją Nacionalinės bibliotekos Valstybingumo erdvėje (II a).\r\nValstybės kategorija pagrįstas viešosios politikos supratimas patiria konceptualių iššūkių, grąžinančių prie klausimo, kas mums valstybė yra šiandien ir kokia ji bus, projektuojant Lietuvos ateities raidą iki 2050-ųjų.\r\nTarp svarstomų temų: ar valstybė šiandiene prasme išliks, ar ir kiek ji bus „liberali“, „piliečių“, „tautinė“, o gal tiesiog – „respublika“? Ar valstybė ir politinė bendruomenė mums vis dar bus tapatu? Kokie piliečių lūkesčiai ir įsipareigojimai valstybei ir politinei bendruomenei? O gal mums pakaks saviraiškos virtualiose bendruomenėse ir socialiniuose burbuluose?\r\nKoks valstybės veikimas prognozuotinas ir projektuotinas globaliai susisaisčiusiame pasaulyje, atsižvelgiant į ryškėjančius tarptautinės sistemos ir galios pokyčius? Koks jos santykis su tarptautinėmis organizacijomis, verslo korporacijomis, migrantų populiacijomis ir diasporomis? Ar ateityje atrasime valstybę pakeičiančias politiškumo formas? Ar šiandien apskritai prasminga kalbėti apie valstybės idėją, o gal idėjas? Jei taip, tai – kokias?\r\nDiskusijos nuoroda į klasikinius filosofinius tekstus sąmoningai siūlo neuždaryti valstybės sąvokos į vienos srities, požiūrio ar prielaidų rėmus, atvirai ir fundamentaliai sugrįžti prie pamatinių politikos klausimų.\r\nDalyviai: Simas Čelutka, Laurynas Peluritis, Simona Merkinaitė, Antanas Terleckas, Domantas Katelė, Ineta Aleknavičiūtė, Dominykas Datkūnas.\r\nModeratorius – istorikas doc. Aurimas Švedas.\r\nDiskusiją stebėti kviečiame ,,Youtube“ paskyroje „Atviras Seimas“.\r\nKviečiame dalyvauti!",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/Apie-valstybe_Vilnius-events-750x600-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Lietuvos nacionalinė Martyno Mažvydo biblioteka",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Gedimino pr. 51",
    "location_url": "http://www.lnb.lt"
  },
  {
    "id": 184277,
    "link": "https://www.vilnius-events.lt/renginiai/paversti-baznycias-priestikikybiniais-muziejais/",
    "date": "2023-04-13 18:00",
    "all_dates": "",
    "title": "Paversti bažnyčias prieštikikybiniais muziejais",
    "content": "Šios ekskursijos pavadinimas - ištrauka iš vieno Vilniaus kunigo pamokslo, nejučia išpranašavusio didelės dalies sostinės katalikų bažnyčių uždarymą ankstyvuoju pokariu.\r\nSandėliai, muziejai, sporto salės, tarp šventųjų statulų burzgiantys sunkvežimiai ar šalia pagrindinio altoriaus besikūrenęs laužas - apie visas šitas bažnyčių metamorfozes išgirsite per 1 valandą 45 minutes trunkantį pasivaikščiojimą, pradėję ties Arkikatedra ir baigdami prie šv. Kotrynos bažnyčios.\r\n\r\nBūtina registracija elektroniniu paštu paulius.zaveckis@gmail.com ar telefonu 8 684 47169 pas gidą Paulių Zaveckį.\r\n\r\n&nbsp;",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/VilniusEventsKelti.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Pradžia &#8211; Katedros aikštės varpinė",
    "location_info": "",
    "category": "Ekskursijos",
    "location_address": "(prie varpinės laiptų)",
    "location_url": ""
  },
  {
    "id": 184696,
    "link": "https://www.vilnius-events.lt/renginiai/paskaita-gyvunai-vilniaus-zemutineje-pilyje-viduramziais/",
    "date": "2023-04-13 18:00",
    "all_dates": "",
    "title": "Paskaita „Gyvūnai Vilniaus Žemutinėje pilyje Viduramžiais“",
    "content": "Vykdant archeologinius tyrimus Vilniaus Žemutinėje pilyje, buvo surinkta daugybė gyvūnų kaulų – iki šiol atlikta daugiau negu 100 000 jų fragmentų tyrimų. Apie pusė radinių buvo aptikta XIII–XV a. sluoksniuose. Tai įspūdingas tyrimų mastas, jų rezultatai leidžia patikimai kalbėti apie pilies gyventojų laikytus ar medžiotus gyvūnus. Apskritai Vilniaus Žemutinę pilį galima įvardinti kaip detaliausiai zooarcheologiškai tyrinėtą vietovę Lietuvoje ir vieną labiausiai ištirtų Europoje. Pilyje rastų gyvūnų tyrimai suteikė unikalios informacijos apie tai, kokius gyvulius augino ir valgė pilies gyventojai, kokius žvėris ir paukščius medžiojo valdovai ir jų aplinka, kokiais arkliais jodinėjo, kuo buvo ypatingi pilies šunys ir kada pilyje gyveno daugiausiai kačių. Gyvenimas pilyje tęsėsi šimtmečiais, archeologiniai ir zooarcheologiniai pilies radiniai tiksliai datuoti, o tai leidžia stebėti, kaip ilgainiui kito pilies gyventojų mitybos ar medžioklės ypatumai, svarstyti apie galimas pokyčių priežastis. Be to, pastaraisiais metais atlikti gyvūnų mitybos tyrimai ir tiesioginis žymiausių pilies gyvūnų radiokarboninis datavimas atskleidė dar daugiau detalių apie gyvūnų ir žmonių gyvenimą pilyje.\r\n\r\nDr. Giedrė Piličiauskienė\r\nRenginys nemokamas, bet būtina registracija <a href=\"https://registracija.valdovurumai.lt/k9t6xdqi\">ČIA</a>\r\nPo renginio klausytojai maloniai kviečiami aplankyti parodą",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/namukas-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Valdovų rūmai",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Katedros a. 4",
    "location_url": "http://www.valdovurumai.lt"
  },
  {
    "id": 184324,
    "link": "https://www.vilnius-events.lt/renginiai/rasos-birutienes-knygos-vieneri-simtmecio-metai-be-civilizacijos-pristatymas/",
    "date": "2023-04-13 18:00",
    "all_dates": "",
    "title": "Rasos Birutienės knygos „Vieneri šimtmečio metai be civilizacijos“ pristatymas",
    "content": "Vilniaus ZONTA moterų klubas maloniai kviečia į klubo narės notarės Rasos Birutienės knygos „Vieneri šimtmečio metai be civilizacijos“ pristatymą Lietuvos nacionalinėje Martyno Mažvydo bibliotekoje balandžio 13 d. 18 val.\r\n\r\n500 puslapių knyga pasakoja apie Lietuvos senojo kaimo papročius. Tai ir metų laikai, jų nulemti kiemo ir lauko darbai, kaimo gyvenimo buitis ir amatai, tradicinės šventės, per kelių kartų istoriją patvirtinantys esminę gyvenimo formulę: šeima, Dievas, Tėvynė.\r\n\r\nAutorės žodžiais kalbant, knyga apie tai, kaip Homo sapiens panaudojo milijonus metų kaupiamas žinias ir atėjo iki civilizacijos aušros. Knyga skirta kiekvienam, norinčiam sužinoti, kaip žmonės gyveno be tokios civilizacijos, kokią turime dabar. Tai patyriminė, gyvenimiška kelionė per kelių kartų gyvenimus, iš kurių visi galime pasisemti naudingų žinių ir permąstyti savo gyvenimo prasmę bei tikslus.\r\n\r\nVilniaus ZONTA klubo misija – vykdyti projektus, kurie stiprintų moterų statusą visuomenės gyvenime ir skatintų jų veiklą bei bendravimą Lietuvoje ir visame pasaulyje. Klubo kasdieniai tikslai yra ugdyti moterų savarankiškumą, skatinti jas užsiimti labdaringa veikla, organizuoti socialiai reikšmingus komunikacinius renginius, puoselėti neformalų bendravimą ir bendradarbiavimą, skatinti tarptautinį bendradarbiavimą.\r\nOrganizacijos pavadinimas kildinamas iš siju genties Lakotos indėnų žodžio, reiškiančio „garbė ir patikimumas“.\r\nLaukiame susidomėjusių Renginių erdvėje, III a.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/RB-knyga-Vilnius-events-750x600-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Lietuvos nacionalinė Martyno Mažvydo biblioteka",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Gedimino pr. 51",
    "location_url": "http://www.lnb.lt"
  },
  {
    "id": 184234,
    "link": "https://www.vilnius-events.lt/renginiai/jogos-sesijos-anglu-kalba/",
    "date": "2023-04-13 18:30",
    "all_dates": "2023-04-13 18:30<br/>2023-04-18 18:30<br/>2023-04-20 18:30<br/>",
    "title": "Jogos sesijos anglų kalba",
    "content": "Kviečiu praktikuotis jogos autentiškoje erdvėje - medinės miesto architektūros muziejuje!\r\nSesijos orientuotos į pradedančiuosius, užsiėmimai vyks anglų kalba nedidelėse grupelėse.\r\n\r\nDaugiau detalių FB renginio nuorodoje <a href=\"https://fb.me/e/3raKnKqX6\">ČIA</a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/Pastel-Tender-Elegant-Aesthetic-Photography-Collage-Facebook-Cover-3-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Medinės miesto architektūros muziejuje",
    "location_info": "",
    "category": "Kiti",
    "location_address": "Polocko g. 52",
    "location_url": ""
  },
  {
    "id": 176515,
    "link": "https://www.vilnius-events.lt/renginiai/stiklinis-zverynas-5/",
    "date": "2023-04-13 18:30",
    "all_dates": "2023-04-13 18:30<br/>2023-05-13 16:00<br/>2023-06-13 18:30<br/>2023-08-13 16:00<br/>",
    "title": "STIKLINIS ŽVĖRYNAS",
    "content": "<h3>Naujasis teatras pristato! Dviejų dalių tragikomedija STIKLINIS ŽVĖRYNAS.</h3>\r\nTai spektaklis pagal XX a. dramaturgijos klasiko amerikiečio Tenesio Viljamso (Tennessee Williams) to paties pavadinimo dramą, kurioje pasakojama vienos šeimos istorija. Jos veikėjai nesugeba realiai mąstyti ir gyventi. Motina paskendusi praeities prisiminimuose, sūnus trokšta romantiškų nuotykių, o dukra užsisklendusi savo stiklinių žvėrelių pasaulyje. Veikėjų sukurtos iliuzijos jiems yra svarbesnės nei tikrovė, kurioje jie jaučiasi bejėgiai ir nesaugūs. Pagrindinė T. Viljamso pjesių tema, pasak jo paties – siekis parodyti neigiamą poveikį, kurį visuomenė daro jautriam, neprisitaikančiam individui.\r\n\r\nVAIDINA:\r\nAmanda VINGFILD (motina) – Šviesa ŠULC\r\nTomas VINGFILDAS (sūnus) – Mantas ZEMLECKAS / Jurijus MAJAUSKAS\r\nLora VINGFILD (duktė) – Žydrūnė DRAGŪNAITYTĖ / Kristina GRŪŠELIONYTĖ\r\nDžimas O’KONORAS (kavalierius) – Jurijus MAJAUSKAS / Marius ČERNIAUSKAS / Oskaras DAINOVSKIS\r\n\r\nVIETA: Naujasis teatras, A. Jakšto g. 9, PIETINIS ĮĖJIMAS, Kamerinė salė, Vilnius.\r\n\r\nBilietus į šį renginį galite įsigyti visose Bileitai.lt platinimo vietose ir Naujojo teatro kasose A. Jakšto g. 9-130, iš anksto suderinus laiką tel. +370 602 27321 arba info@naujasisteatras.lt\r\n\r\nKontaktas: Tel.: +370 602 27321 arba El. paštas: info@naujasisteatras.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2022/11/584abd34bbc19f11cb3bb22d8f8013d2.jpg",
    "event_url": "https://naujasisteatras.lt/",
    "event_email": "info@naujasisteatras.lt",
    "location_name": "Naujasis teatras",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "A. Jakšto g. 9-130",
    "location_url": "http://www.naujasisteatras.lt"
  },
  {
    "id": 178023,
    "link": "https://www.vilnius-events.lt/renginiai/a-kaniavos-monospektaklis-tula-ir-kiti-vilnius/",
    "date": "2023-04-13 18:30",
    "all_dates": "",
    "title": "A. Kaniavos monospektaklis &#8222;Tūla ir kiti&#8221; | Vilnius",
    "content": "&nbsp;\r\n\r\nPjesė balsui ir pianinui palankioje šviesoje\r\nTŪLA IR KITI\r\n(J. Kunčino romano „Tūla“ ir apsakymų motyvais)\r\n\r\n-O apie ką gi rašoma visais laikais? - pasmalsavau.\r\n- Apie meilę , mirtį ir vyną - oriai atsiliepė senutis.\r\n(Jurgis Kunčinas)\r\n\r\nPjesė balsui ir pianinui. Jurgio Kunčino romano „Tūla“ ir apsakymų motyvais. Tai tiesiog pasakojimas apie meilę. Meilę Vilniui ir moteriai. Apie meilę, kuri lyg gelbėjimo ratas padeda gyvenimo dugną pasiekusiam herojui bent laikinai iškilti į paviršių ir įkvėpti gryno oro. Čia meilė – valkatiška ir dieviška, purvina ir tyra, girta ir sąmoninga, nuščiuvusi ir klykianti, bet tai vienintelė galimybė susirasti „kampelį dangaus, kuriame nereikėtų daryti žygdarbių“.\r\n\r\nNesibaigiančių klajonių po aptriušusias Vilniaus senamiesčio gatveles, Kalnų parko krūmynus, apleistus Užupio namus, metu herojus, kurio mes net vardo nežinome, sutinka merginą, vardu Tūla. Trumpas ir tragiškas jų ryšys trunka tik savaitę, bet išlikę prisiminimai padeda herojui jaustis gyvam net tada , kai per greitai prabėgęs gyvenimas negailestingai žvelgia į akis, leisdamas suprasti, kad ateinanti diena jau neatneš nieko naujo. Iš beprotnamių palatų, kalėjimo kamerų, jis naktimis ištrūksta, pasivertęs šikšnosparniu, jis vis grįžta į apleistus Tūlos namus - tą vienintelę vietą, kurioje jautėsi laimingas.\r\n\r\nŠią neįmanomos meilės istoriją savo kūrybos vakaro metu pasakoja Rašytojas. Pasakojimas nevaldomai blaškosi tarp laikmečio, vietovių ir metų laikų, įtraukdamas vis naujus ir naujus margo „tautų katilo“ - Vilniaus ir jo apylinkių gyventojus, persipina su jo savaip interpretuojamomis Hamleto, Otelo, Romeo ir Džiuljetos tragedijomis, kurios, anot Rašytojo, tėra vaikų žaidimas, palyginus su fantastiška žmogaus – šikšnosparnio ir Tūlos meile. Panašumas tik tas, kad visos jos tragiškos.\r\n\r\n„Meilė tik tada pasiekia savo tikslą, kai baigiasi mirtimi, - pasakė budelis ir nukirto jiems galvas“.\r\n\r\nGyvename ne romantikos laikais. Bet sakoma, kad kiekviename mūsų yras išlikę dalelė beviltiško romantiko. „Tūla ir kiti“ - galimybė išsiaiškinti ar tai tiesa?\r\n\r\n______________________________________________________________________________\r\nInscenizacijos autorius, režisierius – Andrius Kaniava\r\nVaidina – Andrius Kaniava\r\nŠviesos režisieriai – Darius Malinauskas, Pijus Vasiliauskas\r\nSpektaklio trukmė: 90 min.\r\n\r\nBilieto kaina: 15 €\r\nBilietus platina KAKAVA ir 1 val. iki spektaklio pradžios prie salės durų\r\n* moksleivių grupėms (nuo 10 asm.) taikomos nuolaidos\r\n** spektaklis skirtas žiūrovams nuo 16 metų\r\n*** lydintis pedagogas gauna nemokamą kvietimą\r\n\r\nKontaktas: alina@bardai.lt 867223266",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2022/11/Web-2-420x591-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus „Lėlės“ teatras",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "Arklių g. 5",
    "location_url": "http://www.teatraslele.lt"
  },
  {
    "id": 184940,
    "link": "https://www.vilnius-events.lt/renginiai/adas-ir-vilte-koncertas-adomo-mickeviciaus-bibliotekoje/",
    "date": "2023-04-13 18:30",
    "all_dates": "",
    "title": "Adas ir Viltė | koncertas Adomo Mickevičiaus bibliotekoje",
    "content": "„Adas ir Viltė“ – tai profesionalaus būgnininko ir elektroninės muzikos prodiuserio Ado Gecevičiaus bei vokalistės Viltės Ambrazaitytės bendras projektas, kuriame originalios Ado kurtos elektroninės muzikos fone skamba Viltės atliekamos lietuvių liaudies dainos. Jųdviejų projekto tikslas – atgaivinti gražius, tačiau jau primirštus lietuvių liaudies kūrinius. Duetas vienija jėgas ir kuria tam, kad lietuvių tautosaka atgimtų naujuose amplua.\r\n\r\nJau daugiau nei prieš dešimtmetį duetas paviešino pirmąjį savo kūrinį – drum&amp;bass stiliumi aranžuotą lietuvių liaudies dainą „Saulelė raudona“. Po to beveik dešimtmetį vyko nuolatinės paieškos ir kūryba: Viltė, dainuodama kolektyvuose „Kūlgrinda“ ir „Žalvarinis“, gilino lietuvių tautosakos žinias ir ieškojo lietuvių liaudies dainų, tinkančių projekto idėjos realizavimui, o Adas, grupių „Sheep Got Waxed“ bei „Vilniaus Energija“ narys, kuriantis ir prodiusuojantis muziką Lietuvos ir užsienio atlikėjams, autentiškas dainas kėlė naujam gyvenimui. Prieš pusantrų metų Adas ir Viltė išleido savo pirmąjį elektroninės lietuvių liaudies muzikos albumą „Dėl žalio žolyno“.\r\n\r\nNuorodos į Ado ir Viltės muziką:\r\n<a href=\"https://youtu.be/KNZoih1ZPcs\">https://youtu.be/KNZoih1ZPcs</a>\r\n<a href=\"https://open.spotify.com/album/6mKvPpbVtn3yeaOfDUcggt\">https://open.spotify.com/album/6mKvPpbVtn3yeaOfDUcggt</a>\r\n___________________\r\nDueto „Adas ir Viltė“ pasirodymas – tai kovo–birželio mėnesiais kas antrą ketvirtadienį bibliotekoje vyksiančio projekto „Koncertai Adomo Mickevičiaus bibliotekoje“ dalis. Projektu tikimasi sukurti sąlygas bibliotekos bendruomenės nariams nemokamai dalyvauti kokybiškuose ir išskirtiniuose koncertuose, susipažinti su rečiau girdima originalia Lietuvos kūrėjų muzika.\r\nProjekto „Koncertai Adomo Mickevičiaus bibliotekoje“ rėmėjai ir partneriai:\r\nAsociacija LATGA, radijas LRT OPUS ir (sub)kultūros e-žurnalas ORE.LT.\r\nĮėjimas į koncertą laisvas, maloniai kviečiame.\r\n\r\nDaugiau informacijos rasite <a href=\"https://www.facebook.com/events/182566757861312\">čia</a>\r\n\r\nKontaktas: kuryboslaboratorija@amb.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/vilnius-events_ADAS-IR-VILTE.jpg",
    "event_url": "",
    "event_email": "kuryboslaboratorija@amb.lt",
    "location_name": "A. Mickevičiaus viešoji biblioteka",
    "location_info": "<p>Paroda nelankoma valstybinių švenčių dienomis</p>",
    "category": "Nemokami renginiai, Vaikams, Kiti",
    "location_address": "Trakų g. 10",
    "location_url": "http://www.amb.lt"
  },
  {
    "id": 184624,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursijos-po-ramuno-ceponio-paroda-vertikale/",
    "date": "2023-04-13 19:00",
    "all_dates": "",
    "title": "Ekskursijos po Ramūno Čeponio parodą „Vertikalė&#8221;",
    "content": "Kviečiame į ekskursijas po dailininko Ramūno Čeponio parodą „Vertikalė\".\r\n\r\nJeigu reikėtų išskirti reikšmingiausius Lietuvos meno istorijai abstrakcionistus, dailininkas Ramūnas Čeponis (g. 1958) neabejotinai būtų vienas iš jų. Santūrus, tylus ir uždaras menininkas savo sunkiasvoriuose paveiksluose užkoduoja tai, ką pats įvardina krikščioniškuoju egzistencializmu. Jo paveikslų reljefai gilūs ir daugiasluoksniai, tarsi oda, pro kurią veržiasi žmogaus esmės paieškos.\r\n\r\nTapytojas, grafikas, iliustratorius R. Čeponis gimė 1958 m. Vilniuje, ten pat gyvena ir kuria. 1976–1982 m. studijavo teatro dekoracijos discipliną LTSR valstybiniame dailės institute (mokėsi pas J. Čeponį, A. Šaltenį, A. Andrijauską, A. Švėgždą). Nuo 1983 m. dalyvauja Lietuvos ir užsienio parodose. Kūryba pristatyta Prancūzijoje, JAV, Argentinoje, Rusijoje ir kitose šalyse. Yra sukūręs scenovaizdžių teatrui. Kūrinių įsigiję privatūs kolekcininkai, taip pat Lietuvos dailės muziejus, Nacionalinis M. K. Čiurlionio dailės muziejus, MO muziejus.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/APRamunasCeponis-Terekas-5-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "AP galerija",
    "location_info": "<p class=\"qtranxs-available-languages-message qtranxs-available-languages-message-lt\">Atsiprašome, šis puslapis galimas tik šiomis kalbomis <a href=\"https://www.vilnius-events.lt/en/helpers/api/\" class=\"qtranxs-available-language-link qtranxs-available-language-link-en\" title=\"EN\">Jungtinių Valstijų Anglų</a>.</p>",
    "category": "Parodos, Ekskursijos",
    "location_address": "Užupio g. 24, Vilnius",
    "location_url": ""
  },
  {
    "id": 184829,
    "link": "https://www.vilnius-events.lt/renginiai/sinkerline-ir-akedya-koncertas-red-cat-klube/",
    "date": "2023-04-13 19:00",
    "all_dates": "",
    "title": "Sinkerline ir Akedya koncertas Red Cat klube",
    "content": "Sinkerline - Progresyvaus roko/metalo grupė, susikūrusi 2019 m. pabaigoje.\r\nDainose lyrinis herojus bando pažvelgti pro vidinio pasaulio paslapčių šydą ir atsakyti į taip rūpimus klausimus, su kuriais gali susitapatinti ir dainų klausytojai. Sielą glostys mistinė energija, o širdį privers plakti žaismingas ritmas.\r\n-------------------------------------------------------------------------\r\nAkedya – naujai susikūrusi, progresyvaus art roko grupė.\r\nGrupės skambesys išsiskiria giliais dainų tekstais, efektuotu elektriniu smuiku, kurio avangardiškas skambesys varijuoja tarp lyrikos ir grotesko, bei dinamiška perkusija, kuri varijuoja nuo akustinės ramybės iki post rokinio šėlsmo.\r\n\r\nNariai:\r\nVokalas, El. Gitara – Majus Takas\r\nBūgnai / Perkusija – Gediminas Tumėnas\r\nEl. Smuikas – Lyja Maknavičiūtė\r\nBosinė gitara – Ramūnas Musteikis\r\n\r\n&nbsp;",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/artwork-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Red Cat",
    "location_info": "",
    "category": "Koncertai",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 181347,
    "link": "https://www.vilnius-events.lt/renginiai/masininkai-keistuoliu-teatras-2/",
    "date": "2023-04-13 19:00",
    "all_dates": "2023-04-13 19:00<br/>2023-05-10 19:00<br/>",
    "title": "Mašininkai | Keistuolių teatras",
    "content": "Murray Schisgal „Mašininkai“\r\n\r\nMoteris ir vyras, kasdien susitinkantys tame pačiame darbe. Tradiciniame darbe, nuo ryto aštuonių iki vakaro penkių, mažame darbo kambaryje, kuriame nuolatos skamba monotoniškas rašomųjų mašinėlių tarškėjimas atliekant vieną ir tą patį veiksmą – rašant potencialių pirkėjų vardus, pavardes bei adresus ant reklaminių atvirukų. Taip savo gyvenimą vienoje kontoroje leidžia Silvija Peiton ir Polis Kaningemas. Moteris ir vyras, beviltiškai bandantys kasdieniuose savo dialoguose prabilti apie tai, kas jaudina, liūdina ir netgi skaudina. Jie beatodairiškai tiki, kad jiems niekuomet neteks daryti to, ko jie nenori, ir kad šis kasdienis „mašininis“ spausdinimas ant atvirukų tėra laikinas jų darbas.\r\n\r\n„Mašininkai“ – spektaklis apie norą gyventi kitaip, apie norą bent trumpam ištrūkti iš kasdienio gyvenimo rutinos kiauto ir sykiu apie didelę baimę ką nors keisti nusistovėjusiame gyvenime. Tai spektaklis apie ambicijas, kurios yra didesnės už patį žmogų.\r\n\r\nRežisierius – Aidas Giniotis\r\n\r\nScenografė ir kostiumų dailininkė – Ramunė Skrebūnaitė\r\n\r\nVaidina – Aldona Vilutytė ir Dalius Skamarakas\r\n\r\nSpektaklio rėmėjas – Kultūros ir sporto rėmimo fondas\r\n\r\nTrukmė – 1 valanda 15 minučių\r\n\r\nPremjera – 2008 m. spalio 3 d.\r\n\r\nN–14\r\n\r\nSpektaklis yra Vilnius 700 programos dalis.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/02/1500_200_5dee4f85247b3-1.jpg",
    "event_url": "https://bilietai.keistuoliai.lt/event/22?fbclid=IwAR0pwzosJGpHfIFe3lz6lXpQ0Gf5utbsnUQGewKroWVCTOpY76WC_Z3u7v8",
    "event_email": "",
    "location_name": "Keistuolių teatras",
    "location_info": "",
    "category": "Vilnius 700, Spektakliai",
    "location_address": "Laisvės pr. 60",
    "location_url": "http://www.keistuoliai.lt"
  },
  {
    "id": 184540,
    "link": "https://www.vilnius-events.lt/renginiai/jaunosios-danijos-zvaigzdes/",
    "date": "2023-04-13 19:00",
    "all_dates": "",
    "title": "Jaunosios Danijos žvaigždės",
    "content": "Festivalis \"Europa Vilniui\" pristato koncertą “Jaunosios Danijos žvaigždės”. Jauni, bet jau daugybės tarptautinių konkursų laurus spėję nuskinti pianistai iš Danijos, pristato spalvingą, nuotaikingą programą, kurioje skambės J. S. Bach, F. Chopin, J. Haydn, F. Schubert - F. Liszt, F. Mendellsohn Bartholdy, A. Pieczonka, D. Scarlatti kūriniai.\r\n\r\nFestivalio organizatorius - Vilniaus rotušė\r\nPartneris - Vilniaus savivaldybė\r\nInformacinis partneris - JCDecaux\r\n\r\nBilietus galite įsigyti <a href=\"https://www.bilietai.lt/lit/renginiai/koncertai/jaunosios-danijos-zvaigzdes--a-darvann-hermann-a-gaub-pedersen-e-dalgaard-a-roman-384919/\">čia.</a>\r\n\r\n<strong>Kontaktas:</strong> info@vilniausrotuse.lt +370 5 261 8007",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/Untitled-design-2023-03-29T135924.271.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus rotušė",
    "location_info": "<p>Valstybinių švenčių dienomis rotušė nedirba</p>",
    "category": "Koncertai",
    "location_address": "Didžioji g. 31",
    "location_url": "http://www.vilniausrotuse.lt"
  },
  {
    "id": 184979,
    "link": "https://www.vilnius-events.lt/renginiai/tradiciniu-sokiu-mokymai-ir-vakarone/",
    "date": "2023-04-13 19:30",
    "all_dates": "2023-04-13 19:30<br/>2023-04-20 19:30<br/>2023-04-27 19:30<br/>",
    "title": "Tradicinių šokių mokymai ir vakaronė",
    "content": "Mielieji,\r\nTradicinių šokių klube ateinantį ketvirtadienį balandžio 13 d. nuo 19:30 tradicinių lietuviškų šokių mokymai, vėliau - tradicinė šokių vakaronė iki 22:30.\r\nLaukiame visų šokėjėlių! Pakvieskite savo draugus ir visus besidominčius tradiciniais šokiais.\r\n\r\nTradicinių šokių klubo renginiai ketvirtadieniais vyksta Sostinės vaikų ir jaunimo centro (Konstitucijos pr. 25) Mėlynojoje salėje III a.\r\n\r\nDaugiau informacijos galite rasti <a href=\"https://www.facebook.com/Tradiciniu.sokiu.klubas/?locale=lt_LT\">čia.</a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/TSK-skelbimui-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Lietuvos vaikų ir jaunimo centras",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Konstitucijos pr. 25",
    "location_url": "http://www.lvjc.lt"
  },
  {
    "id": 184090,
    "link": "https://www.vilnius-events.lt/renginiai/karaoke-thursdays-at-la-birra-pub/",
    "date": "2023-04-13 23:30",
    "all_dates": "2023-04-13 23:30<br/>2023-04-20 23:30<br/>2023-04-27 23:30<br/>2023-05-04 23:30<br/>2023-05-11 23:30<br/>2023-05-18 23:30<br/>2023-05-18 23:30<br/>2023-05-25 23:30<br/>",
    "title": "Karaoke Thursdays at La Birra Pub",
    "content": "Dainuoji ne tik duše? Pats laikas į karaokę! Tai puiki pramoga drąsiems ir pasilinksminti mėgstantiems žmonėms.\r\nKetvirtadienio vakarais Vilniaus g. įsikūrusiame “La Birra”Pub rusyje vyksta karaoke vakarai. Gera nuotaika, atsipalaidavęs jaunimas , užsienio svečiai, visi linksmai iki paryčių traukia gerai žinomas dainas. Neerzinkite KAIMYNŲ, ateikite pas mus.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/322555793_1230079434526401_3097391571995739645_n.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "La Birra PUB",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Vilniaus g. 29",
    "location_url": "https://facebook.com/labirrapub"
  },
  {
    "id": 184983,
    "link": "https://www.vilnius-events.lt/renginiai/vyksmas-ir-veiksmas-aplink-traku-vartus/",
    "date": "2023-04-14 16:00",
    "all_dates": "",
    "title": "Vyksmas ir veiksmas aplink Trakų vartus",
    "content": "Kviečiu į ekskursiją, kurioje supažindinsiu su beveik 300 metų Vilniaus miestą saugojusiais Trakų vartais ir kas vyko ir dar vyksta šalia jų. Bus įdarbinti bent 4 pojūčiai. Laukia prizai ir siurprizai. Maršrutas beveik žiedinis: ekskursijos pradžia - prie Mo muziejaus sode esančio raudono žirgo skulptūros, pabaiga- Švč. Mergelės Marijos Ėmimo į dangų (pranciškonų) bažnyčios Trakų g. šventoriuje.\r\n\r\n<strong>Registracija</strong> el. paštu lietuvosgide@gmail.com ir išankstinis apmokėjimas būtini, nes nuo jų priklauso, ar ekskursija vyks.\r\n\r\nDaugiau informacijos galite rasti <a href=\"https://www.facebook.com/Atrasksavokrasta\">čia.</a>\r\n\r\n&nbsp;",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/20221018_165937-scaled-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "MO muziejus",
    "location_info": "",
    "category": "Po atviru dangumi, Ekskursijos",
    "location_address": "Pylimo g. 17",
    "location_url": "http://www.momuziejus.lt"
  },
  {
    "id": 184093,
    "link": "https://www.vilnius-events.lt/renginiai/fridays-at-la-birra-pub/",
    "date": "2023-04-14 17:00",
    "all_dates": "2023-04-14 17:00<br/>2023-04-21 17:00<br/>2023-04-28 17:00<br/>2023-05-05 17:00<br/>2023-05-12 17:00<br/>2023-05-19 17:00<br/>2023-05-26 17:00<br/>",
    "title": "Fridays at La Birra Pub",
    "content": "Penktadieniai La Birra Pub'e - tai smagiausia vieta pradėti jūsų savaitgalio istoriją!\r\nJauki ir draugiška aplinka, juokas, gyvi atlikėjų pasirodymai ir šokiai iki ryto su Dj ir geriausia visų laikų muzika.\r\nBaras siūlo platų gėrimų asortimentą, tad rasite savo mėgstamiausią. Taip pat galite pasimėgauti ir gardžiais užkandžiais!\r\nTad nesikuklink ir prisijunk prie smagiausio vakarėlio mieste!",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/322179467_5428589177252897_446829535905213859_n.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "La Birra PUB",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Vilniaus g. 29",
    "location_url": "https://facebook.com/labirrapub"
  },
  {
    "id": 184096,
    "link": "https://www.vilnius-events.lt/renginiai/disco-saturdays-at-la-birra-pub/",
    "date": "2023-04-14 17:00",
    "all_dates": "2023-04-14 17:00<br/>2023-04-21 17:00<br/>2023-04-28 17:00<br/>2023-05-05 17:00<br/>2023-05-12 17:00<br/>2023-05-19 17:00<br/>2023-05-26 17:00<br/>",
    "title": "Disco Saturdays at La Birra Pub",
    "content": "Savaitgalio pratęsimas tik pas mus!!\r\nGera muzika, šaltas alus ir šokiai iki ryto!!\r\nDj pasistengs, jog judėtumėte iki pat ryto!!",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/323267371_493601166237200_6209772153514857115_n.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "La Birra PUB",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Vilniaus g. 29",
    "location_url": "https://facebook.com/labirrapub"
  },
  {
    "id": 180776,
    "link": "https://www.vilnius-events.lt/renginiai/spektaklis-be-zodziu-jaunimui-ir-suaugusiems-doriano-grejaus-portretas-2/",
    "date": "2023-04-14 18:30",
    "all_dates": "",
    "title": "Spektaklis be žodžių jaunimui ir suaugusiems &#8221;Doriano Grėjaus portretas&#8221;",
    "content": "Airių rašytojas Oscaras Wilde‘as garsėjo savo žavesiu ir ekstravagancija – tiek savo kūrybos, tiek ir gyvenimo estetizmu. Būdamas 34 metų jis išleido knygą „Laimingasis princas ir kitos pasakos“ – nuo to laiko ir tapo gerai žinomu autoriumi. Jo vienintelis romanas „Doriano Grėjaus portretas“, pirmą kartą išspausdintas 1890 m., galima sakyti, taip pat parašytas pasakos forma. Tačiau šį kartą turinys gerokai niūresnis... Ir nieko keisto, kad po jo paskelbimo kilo skandalas: reikalauta jį uždrausti ir nuteisti autorių už amoralaus gyvenimo būdo propagavimą.\r\n\r\nSpektaklio „Doriano Grėjaus portretas“ kūrybinę grupę sudaro žinomos lėlių teatro menininkės, su kurių bendro darbo rezultatais „Lėlės“ žiūrovai jau pažįstami: 2014 m. G. Radvilavičiūtės kartu su scenografe Renata Valčik, choreografe Sigita Mikalauskaite ir kompozitore Rita Mačiliūnaite sukurtas spektaklis „Smėlio žmogus“ pelnė Auksinį scenos kryžių, sėkmingai rodomas teatro repertuare ir nuolat kviečiamas atstovauti Lietuvos kultūrą tarptautiniuose teatro festivaliuose. Naujasis spektaklis tarytum pratęsia jau „Smėlio žmoguje“ pradėtą gvildenti žmogaus asmenybės dvilypumo ir jo savidestrukcijos temą.\r\n\r\n„Žiūrėdamas į paveikslą žmogus įžengia į kitą laiką. Laikas prasiplečia. Portrete žmogus atpažįsta save patį. Žiūrėjimas į portretą – tarsi žiūrėjimas į veidrodį. Veidrodis žmogui suteikia unikalią galimybę matyti save, savo veidą, savo akis, ir sudaro sąlygas dialogui su pačiu savimi. Žiūrėdamas į išorę žmogus mato savo vidų. Žiūrėdamas į veidrodį žmogus gali pakliūti į kitą pasaulį. Ir šie du pasauliai gali susiliesti. Žiūrėdami į veidrodį mes galime pamatyti tai, kas tiesiogiai mūsų žvilgsniui neprieinama. Veidrodžio gylis mums sako, kad mes galime pamatyti kur kas daugiau arba visai kitaip, nei matome savo realybėje. Veidrodis yra mūsų asmeninis dabarties portretas.\r\n\r\nŠiandien žmogų supa labai daug veidrodžių, t.y. atspindinčių paviršių – nuo tikrų veidrodžių ir langų iki ežerų ir balų, snaigių, akmens anglies gabalėlių ir t. t. Visi jie sukuria matomo pasaulio, daiktinio audinio įtrūkius, tai – tarsi langai į kitą pasaulį. Tačiau perdėtas susikoncentravimas į save ir savo fizinę išvaizdą – kelias į tuštybę, savimeilę, pasipūtimą, išpuikimą, egocentrizmą. Be meilės, artimų žmonių, ėjimo kartu, grožis, sėkmė nieko nereiškia. Nemielas gyvenimas nuolat žiūrint į save.\r\n\r\nIki šiol kai kuriose pirmykštėse gentyse tikima, kad veidrodis gali pavogti sielą.“ – mintimis dalinasi spektaklio režisierė Gintarė Radvilavičiūtė.\r\nRežisierė, dailininkė: Gintarė Radvilavičiūtė\r\n\r\nKontaktas: Tel.: 8 5 261 40 17; El. p.: info@teatraslele.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/Dorianas-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus „Lėlės“ teatras",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "Arklių g. 5",
    "location_url": "http://www.teatraslele.lt"
  },
  {
    "id": 184975,
    "link": "https://www.vilnius-events.lt/renginiai/justo-tertelio-autoriniu-dainu-koncertas-prabudiman/",
    "date": "2023-04-14 19:00",
    "all_dates": "",
    "title": "Justo Tertelio autorinių dainų koncertas | PraBudiMan",
    "content": "Dainų autorius ir atlikėjas, aktorius, dramaturgas ir režisierius Justas Tertelis kviečia į akustinį vakarą. Jo metu gyvai atliks aktorines, scenines, užkulisines, socialines, asmenines ir viešas dainas bei pristatys debiutinį albumą „PraBudiMan”. J. Tertelio autorinėje muzikoje ir tekstuose atsispindi žanrų bei temų įvairovė. Teatriniame atlikime su kiek aštresniu, ironišku santykiu žvelgiama į šiandieną.\r\n\r\nApie autorių:\r\nJustą Tertelį galima išvysti „Keistuolių teatro“ ir teatro laboratorijos „Atviras ratas“ scenose bei kitų teatrinių projektų produkcijose. Taipogi jis rašo pjeses, režisuoja spektaklius, o jo kūryba pripažinta aukščiausiais įvertinimais Lietuvoje. Jis aktyviai veikia švietimo lauke, kaip edukatorius, ugdymo procesų fasilitatorius, dirba asociacijos „Kūrybinės jungtys“ kuratorių komandoje, taip pat buvo LRT tinklalaidžių ciklo „Savo galva“ autorius ir vedėjas. Autorines dainas ir tekstus teatrui J. Tertelis kuria nuo pat savo teatrinės karjeros pradžios (2006 metų). Kaip dainų autorius ir atlikėjas jis dalyvavo festivaliuose „Purpurinis vakaras“, „Tai aš“, „Senamiesčio žiogas“ ir „Akacijų alėja“ bei įvairiuose kituose renginiuose, laidose televizijos ir radijo eteryje.\r\n\r\nBilietu kviečiame pasirūpinti iš anksto <a href=\"https://rb.gy/qhjiob\">čia.</a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/JT-autorinis-koncertas_1600x900-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Teatras Atviras Ratas",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "Ašmenos g. 8",
    "location_url": "http://atvirasratas.lt"
  },
  {
    "id": 184271,
    "link": "https://www.vilnius-events.lt/renginiai/monospektaklis-buti/",
    "date": "2023-04-14 19:00",
    "all_dates": "",
    "title": "Monospektaklis „BŪTI“",
    "content": "Monodramos „Būti“ epicentre – jauna mergina Elena, kuri pirmą kartą gyvenime pati turi priimti svarbų, tačiau netikėtą ir labai sudėtingą sprendimą. Žinia apie neplanuotai užsimezgusią gyvybę priskiriama prie didžiausių gyvenimo sukrėtimų, nes sprendimo akimirką žmogus suvokia, kad gyvenimas bet kuriuo atveju pasikeis negrįžtamai. Pasimetus dėl patiriamo streso Elena užsirašo abortui, tačiau prieš tai yra pakviečiama apsilankyti konsultacijoje, kur specialistės patvirtintų jos apsisprendimą. Elena nė nenutuokia, kad šis vizitas bus lemtingas.\r\n\r\nDovilės Katiliūtės sukurtos spektaklio dramaturgijos pagrindas – tikros moterų, susidūrusių su neplanuotu nėštumu ar abortu, istorijos. Dokumentinė medžiaga suteikia pjesei intymumo, autentiškumo, atskleidžia itin jautrias temas, kuriomis visuomenėje kalbėti dažnai nepatogu. Ką pasirinkti? Nėštumo nutraukimą ar gimdymą neturint jokios paramos? Spektaklyje atskleidžiami būties ieškojimai - kaip „būti“? Kaip gyventi su savo pasirinkimu? Kaip kovoti su šių pasirinkimų psichologinėmis pasekmėmis, nugalint socialinę atskirtį ar vienišumą. Ką mums reiškia būti? Ar mes iš tiesų esame? Ar mes turime teisę spręsti, ar gali būti kiti? O gal sprendimo metu yra tik kiti?\r\n\r\nSpektaklio baigiamoji dalis – su neplanuotu nėštumu ar abortu susidūrusių žmonių fotografijų paroda „Esu“, kurią lydės tikros jų istorijos. Dokumentinė paroda skirta atskleisti realius šio reiškinio mąstus šiandieninėje Lietuvoje. Po spektaklio žiūrovai turės galimybę pasinerti į gyvus, be galo jautrius ir tikrus liudijimus, kurie teatro fikciją perkels į realybę primenant, jog teatras tėra melas apie tiesą, o gyvenime režisieriai esame mes patys.\r\n\r\nRežisierė L. Krivickaitė – „Spektaklyje gausu dviprasmiškumo, šmaikščių situacijų bei nesusipratimų, dažnai žmonės vengia sunkiomis temomis kalbėti atvirai. Spektaklyje vyraujanti pakili nuotaika, komiškos situacijos bei humoras tarsi natūrali pagrindinės herojės apsaugos priemonė. Užuot moralizavę ar gazdinę problema, mes ją pateikiame kaip natūralų, žmogaus suformuotą reiškinį, kuris prasidėjo atsiradus galimybei kontroliuoti žmonijos gimstamumą. Neplanuotas nėštumas ar aborto reiškinys iš pažiūros labai tamsios temos, tačiau pasirinkus tinkamą pažinties būdą ši istorija pasakojama edukuojant žiūrovą, skatinant jį permąstyti savo atsiradimą bei tikslą šiame pasaulyje. Žmogiškasis skausmas dažnai priverčia atsigręžti į esmines vertybes, todėl spektaklyje daug meilės ir šviesos, o pasirinkti, būti ar ne- kiekvieno asmeninis reikalas.“\r\n\r\nBūti negalima nebūti. – kur dėsime kablelį?\r\n\r\nRežisierė : Livija Krivickaitė\r\n\r\nAktoriai: Jūratė Martinaitytė\r\n\r\nScenografijos ir kostiumų dailininkė : Aistė Alksnytė\r\n\r\nDramaturgė : Dovilė Katiliūtė\r\n\r\nŠviesų dailininkai: Kristupas Biržietis\r\n\r\nParodos fotografas : Rytis Aliukonis",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/335506438_146776088307730_661089456351352517_n-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Menų spaustuvė",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "Šiltadaržio g. 6",
    "location_url": "http://www.menuspaustuve.lt"
  },
  {
    "id": 184318,
    "link": "https://www.vilnius-events.lt/renginiai/seiko-sokio-teatro-spektaklis-la-calash-la-latin-lt-2/",
    "date": "2023-04-14 19:00",
    "all_dates": "",
    "title": "Šeiko šokio teatro spektaklis „La Calash La Latin-LT“",
    "content": "2022 Auksiniam scenos kryžiui už vaidmenį šiame šokio spektaklyje nominuota Oksana Griaznova.\r\n\r\nSpektaklyje susitinka du kontrastingi šokio pasauliai – sportinių ir šiuolaikinis. Iš šio susidūrimo gimsta nepatogios, komiškos ir net absurdiškos situacijos.\r\nLyg veidrodžiai vienas kitam, žanrai pabrėžia svarbų momentą apie mūsų troškimą būti kartu ar atskirai, priklausyti bendruomenei ar būti savarankiškais. Sportiniuose šokiuose kiekvienas dalyvis turi savo vaidmenį: poroje – vyras arba moteris, grupėje – į grupės sinchroną įsiliejanti dalis. Tuo tarpu šiuolaikiniame šokyje daugiau individualios judesio raiškos, o lyčių vaidmenys dažnai persimaišę ar tiesiog neakcentuojami.\r\n„La CALASH La Latin-LT“ judesinė medžiaga kuriama pasitelkiant sportinių šokių pozas bei choreografo Palle Granhøj autorinę obstrukcijos techniką. Tai leidžia choreografui transformuoti judesius, ribojant jų veiksmus ir taip atskleisti giluminius asmenybės sluoksnius bei specifinį kiekvieno atlikėjo fiziškumą.\r\nKad ir kurio šokio žanro gerbėjas esate, spektaklis įtrauks žaisminga ir smalsumą žadinančia atmosfera, kuriama skirtingų šokėjų asmenybių.\r\nŠis spektaklis sukurtas pagal „La CALASH La Latin“ – kūrinį, kurio premjera įvyko 1997 m. Danijoje ir choreografui Palle Granhøj atnešė tarptautinę sėkmę su daugiau nei 100 pasirodymų visame pasaulyje. 2022 metais kūrinys šventė 25 metų jubiliejų.\r\n\r\nPalle Granhøj spektaklis\r\nŠokėjai: Dovilė Binkauskaitė, Darius Berulis, Niels Claes, Mantas Ūsas, Oksana Griaznova, Gintarė Marija Ščavinskaitė, Agnija Šeiko, Mantas Stabačinskas, Marius Pinigis, Inga Kuznecova, Viktorija Zobielaitė\r\nŠviesų dizaineris: Aurelijus Davidavičius\r\nMuzika: Yma Sumac, Pérez Prado, Serge Gainsbourg, Camila Cabello\r\nŠeiko šokio teatro meno vadovė, spektaklio konsultantė: Agnija Šeiko\r\nProdiuserės: Sigrid Aakvik, Goda Giedraitytė\r\nProdukcijos komanda: Edita Grigaitienė, Greta Seiliūtė, Austėja Laurinavičiūtė\r\nKoprodiuseriai: Granhøj Dans (DK), Šeiko šokio teatras (LT)\r\n\r\nTeatro veiklą finansuoja: Lietuvos kultūros taryba, Klaipėdos miesto savivaldybė, Danijos meno fondas\r\n\r\nPartneriai: Ainos studija, sportinių šokių klubas „Žuvėdra“, UAB „Puantas“",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/308235608_327655942910682_3970245437463656228_n-2.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Menų spaustuvė",
    "location_info": "",
    "category": "Spektakliai",
    "location_address": "Šiltadaržio g. 6",
    "location_url": "http://www.menuspaustuve.lt"
  },
  {
    "id": 184845,
    "link": "https://www.vilnius-events.lt/renginiai/istoriju-pasakojimo-sal-i-onas-35-2/",
    "date": "2023-04-14 19:00",
    "all_dates": "",
    "title": "Istorijų pasakojimo sal(i)onas (#35)",
    "content": "Balandžio 1-oji – melagių, pramanų ir išdaigų diena nuo seno minima tiek pasaulyje, tiek Lietuvoje. Šįkart, nors ir keliomis dienomis vėliau, bet kviečiame pasiklausyti arba papasakoti istorijų apie pramanus, su kuriais susidūrėte. Kokį balandžio 1-osios įtikinamiausią pramaną esate sugalvoję ir įgyvendinę? O gal jus kas nors yra įsimintinai apgavęs ar įspūdingai papokštavęs? Šiame istorijų pasakojimo sal(i)one galite pasakoti visiškai IŠGALVOTAS istorijas, o mes galėsime spėti ar pasakojimas yra tiesa, ar melas. Žinoma, melas ir apgavystės mus supa ne tik 1-ąją balandžio dieną. Galbūt turite kitokių istorijų apie melagius, galbūt jos ne visai linksmos, bet vis tiek vertos būti papasakotomis?\r\n\r\nInteraktyvaus istorijų pasakojimo teminio vakaro šeimininkė Milda Varnauskaitė kviečia prisijungti į jau 35-ąjį VU Kultūros centro organizuojamą sal(i)oną! Tai ne tik neįpareigojanti istorijų pasakojimo ir klausymosi vieta, kur galima išgirsti ne vieną intriguojantį pasakojimą, bet ir renginys, kuriame galima drąsiai bendrauti su įdomiais dalyviais bei susipažinti su bendraminčiais.\r\nTam, kad žinotume kiek kėdžių ir arbatos puodelių paruošti, reikalinga registracija visiems dalyviams – klausytojams ir pasakotojams <a href=\"https://forms.office.com/r/RZE4uDt35J\">ČIA </a>\r\n\r\nKiekvienas susitikimas sal(i)one būna vis kitoks – naujos, dar negirdėtos, ir kartais labai įkvepiančios ar net pamokančios istorijos. Kaip ir visada sal(i)onas atviras Jūsų istorijoms, todėl jei norite ne tik paklausyti, bet ir papasakoti, registruokitės el.paštu: storytellingvu@gmail.com",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/event-cover-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "VU Istorijos fakultetas",
    "location_info": "",
    "category": "Nemokami renginiai, Kiti",
    "location_address": "Universiteto g. 7",
    "location_url": "http://www.if.vu.lt"
  },
  {
    "id": 181321,
    "link": "https://www.vilnius-events.lt/renginiai/c-gabalis-ir-pelenai-bryan-adams-project-legendos-klubas/",
    "date": "2023-04-14 19:00",
    "all_dates": "",
    "title": "Č. Gabalis ir Pelenai | „Bryan Adams project“ | Legendos klubas",
    "content": "ČESLOVAS GABALIS ir grupė PELENAI pristatys koncertinę programą BRYAN ADAMS PROJECT. Nepriekaištingas muzikos atlikimas bei unikalus, ausį glostantis Česlovo Gabalio balso tembras leis kiekvienam klausytojui pasijusti lyg tikrame atlikėjo Bryan Adams koncerte.\r\nDviejų dalių pasirodymas buvo brandintas ne vienerius metus ir vis dar yra originaliai atnaujinamas. Šis projektas labai greitai pelnė plataus gerbėjų rato pripažinimą – ir nenuostabu, juk lietuviško roko legendų – grupės „Pelenai“ – charizma ir profesionalumas bei žinomų dainų skambesys garantuoja sėkmę.\r\n„Tai nėra muzikinė programa, kurią atliekame dažnai, - dalinasi grupės „Pelenai“ siela Gintas Banys, - o ir pats dainų atrankos procesas buvo tikrai sudėtingas. Rinkomės tuos kūrinius, kurie yra gerai žinomi publikai, mylimi, bet tai ne vienintelis kriterijus. Įtraukėme ir dainas, kurios patinka mums patiems“. Pasak jo, muzikiniai sprendimai atitiks originalius dainų įrašus, kurių žmonės pripratę klausytis. Koncerte suskambės dainos „I do it for you“, „Hey Honey I'm Packing You In“, „Summer of '69“, „ 18 'til I die“ ir kitos.\r\nScenoje pasirodysiantys Česlovas Gabalis (vokalas), Gintas Banys (bosinė gitara), Audrius Piragis (gitara), Saulius Didžiulis (klavišiniai), Vaidotas Taurinskas (mušamieji), Žaneta Taurinskienė (pritariamasis vokalas) kvies roko gerbėjus pasileisti plaukus ir pašėlioti iš širdies.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2022/01/pelenai_kakava_renginio_kompui-01-1024x576-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Legendos klubas",
    "location_info": "",
    "category": "Koncertai",
    "location_address": "Kalvarijų g. 85",
    "location_url": ""
  },
  {
    "id": 182788,
    "link": "https://www.vilnius-events.lt/renginiai/labanakt-mama-keistuoliu-teatras-3/",
    "date": "2023-04-14 19:00",
    "all_dates": "2023-04-14 19:00<br/>2023-05-05 19:00<br/>2023-05-26 19:00<br/>",
    "title": "Labanakt, mama | Keistuolių teatras",
    "content": "„Labanakt, mama“ – tai vienos dalies tragikomiškas spektaklis, statytas pagal amerikiečių rašytojos Marsha Norman pjesę. Spektaklis prasideda iš pirmo žvilgsnio įprastą, kasdienės monotonijos ir buities persmelktą vakarą, kurį motina Telma ir dukra Džesė leidžia kartu. Tik į įprastą ir atpažįstamą rutiną staiga įsiterpia Džesės žodžiai apie planuojamą savižudybę. Ši žinia tampa atskaitos tašku, priverčiančiu veikėjas su didesne atida pažvelgti vienai į kitą, iš naujo apmąstyti gyvenimą ir mirtį.\r\n\r\nSpektaklio kūrėjos, narpliodamos šios keistos situacijos priežasčių grandinę, ieško būdų suvokti jautrius, kartais absurdo spalvomis nuspalvintus ryšius su pačiais artimiausiais. Spektaklyje žiūrovai kviečiami kartu mąstyti apie reikšmingą, bet dažnai taip ir neužduodamą klausimą – ar yra įmanomas dviejų žmonių atviras ir nuoširdus pokalbis, kai pagrindinė jo sąlyga yra pabandyti iš tikrųjų išgirsti vienam kitą?\r\n\r\nRežisierė Ieva Stundžytė\r\n\r\nVaidina: Ilona Balsytė, Diana Kamarauskaitė/Lyja Maknavičiūtė\r\n\r\nScenografė ir kostiumų dailininkė Laura Luišaitytė\r\n\r\nKompozitorius Aidas Giniotis\r\n\r\nŠviesų dailininkas Darius Malinauskas\r\n\r\nTrukmė 1 val. 30 min.\r\n\r\nN – 14\r\n\r\nPROJEKTĄ FINANSUOJA LIETUVOS KULTŪROS TARYBA.\r\n\r\nSpektaklis yra Vilnius 700 programos dalis.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/324096901_1335493380621259_2288193409961583709_n.png",
    "event_url": "https://bilietai.keistuoliai.lt/event/97?fbclid=IwAR264sfQUXiLezByzA2UbjwPl6OduviVAfVXN-Npyr40ekcDBGerF4A7_aM",
    "event_email": "",
    "location_name": "Keistuolių teatras",
    "location_info": "",
    "category": "Vilnius 700, Spektakliai",
    "location_address": "Laisvės pr. 60",
    "location_url": "http://www.keistuoliai.lt"
  },
  {
    "id": 184936,
    "link": "https://www.vilnius-events.lt/renginiai/jazz-duo-leonidas-mieldazis-pianinas-vytautas-pilibavicius-trombonas/",
    "date": "2023-04-14 20:00",
    "all_dates": "",
    "title": "JAZZ DUO:  Leonidas Mieldažis – pianinas, Vytautas Pilibavičius – trombonas",
    "content": "Gyvas džiazas – džiazuojančioms sieloms!\r\nPenktadieniais ir šeštadieniais svetainėje-bare \"Veranda\" laukiame visų, gyvenime pasiilgusių džiazo, arba gyvenančių džiazo ritmu!\r\n\r\nJAZZ DUO\r\nLeonidas Mieldažis – pianinas\r\nVytautas Pilibavičius – trombonas\r\n\r\nLeonidas Mieldažis - klavišininkas, džiazo pianistas ir pedagogos. Baigė Lietuvos Muzikos Akademiją. Grojo ivairiuose muzikos projektuose, kolektyvuose: „Sufle“, „Goldien Melodies“, „Gėlių Vaikai“, „Monkes Blues“, „The Road Band“. Yra dalyvavęs įvairių stilių festivaliuose, bendradarbiavo įrašant kelias dešimtis albumų. Su A. Fedotovo instrumentinių ansamblių dalyvavo įrašant Vygando Telksnio, Benjamino Gorbulskio, Algimanto Raudonikio vinilines plokšteles. Solinę karjerą pradėjo Italijoje Piano baruose. Koncertavo Lenkijoje, Varšuvos klubuose.\r\nŠiuo metu dirba Vilniaus Kolegijoje ir Vilniaus Konservatorijoje.\r\nIšleido tris solinius albumus, kuriuose dalyvavo Vytautas Labutis, Gediminas Laurinavičius,Valerijus Ramoška, DJ Mamania ir kt.\r\n\r\nVytautas Pilibavičius - trombonininkas ir kompozitorius. Lietuvos muzikos ir teatro akademijoje (LMTA) baigė trombono ir pučiamųjų orkestro dirigento klasę, vėliau kompozicijos klasę, stažavosi Kelno konservatorijoje. „London bridge ensemble“ narys, „Rūdiškių brass band“ vadovas, Vilniaus konservatorijos ir kolegijos dėstytojas.\r\n1982 – 1995 m. grojo ir dirbo asistentu V. Čekasino vadovaujamuose kolektyvuose. 1995 m. Anglijos muzikos leidykloje LEO RECORDS išleistas jo solinis albumas „Frontiers“. Muzikos ansamblio „Ex tempore“ įkūrėjas. 2008 – 2011 m. vadovavo Šiaulių miesto pučiamųjų orkestrui.\r\n\r\nRekomenduojame staliukus rezervuoti iš anksto:\r\n- rezervacijos iki 6 svečių +370 5 2730107\r\n- rezervacijų nuo 7 svečių derinimas - rezervacija@veranda.lt\r\n\r\n„Veranda“ – džiazuojame skaniai!\r\n\r\n&nbsp;",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/Jazz-duo-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Svetainė &#8211; baras „Veranda“",
    "location_info": "",
    "category": "Koncertai",
    "location_address": "Kęstučio g. 39",
    "location_url": "http://www.veranda.lt"
  },
  {
    "id": 161861,
    "link": "https://www.vilnius-events.lt/renginiai/stebuklai-vilniaus-pozemiuose-4/",
    "date": "2023-04-15 10:30",
    "all_dates": "2023-04-15 10:30<br/>2023-04-29 10:30<br/>",
    "title": "Stebuklai Vilniaus požemiuose",
    "content": "Leiskitės į intriguojančią kelionę laiku senojo Vilniaus požemiais! Nustebsite, kiek daug netikėtų atradimų, paslapčių ir stebuklų slepia požeminis pasaulis...\r\n\r\nEkskursiją pradėsime nuo turtingiausių ir įspūdingiausių Vilniaus Katedros požemių, ten pamatysite, kur ir kaip buvo laidojami Lietuvos galingiausieji, kur stovėjo pirmoji Katedra ir kas jai nutiko, sužinosite, kokios mįslės gaubia Vytauto Didžiojo kapą ir kokio stebuklo dėka Katedros požemiuose išliko karališkieji palaidojimai, kuris valdovas Katedros požemiuose “paliko” savo širdį ir kur paslėptos karališkosios brangenybės. Turėsite išskirtinę galimybę savo akimis pamatyti seniausią freską Lietuvoje bei išgirsti neįtikėtiną jos atradimo istoriją. Na, ir be abejo, aplankysite legendinės gražuolės Barboros Radvilaitės amžino poilsio vietą, sužinosite, kaip iš tiesų atrodė gražiausia XVI a. Europos moteris ir kas pasiglemžė karalienės gyvybę.\r\n\r\nEkskursijos metu taip pat aplankysime Šv. Kazimiero koplyčią, saugančią šventojo karalaičio Kazimiero Jogailaičio palaikus. O pati koplyčia pelnytai vadinama vienu gražiausių baroko paminklų Lietuvoje. Ekskursiją tęsime Gintaro galerijoje-muziejuje, kur pamatysite kaip prieš 50 mln. metų formavosi gintaras, kokių spalvų jis būna ir kaip mūsų protėviai gintaru papirkinėjo dievus. Taip pat sužinosite paslaptį, kaip atskirti tikrą gintarą nuo padirbinių. Na, ir galiausiai aplankysime vieno iš senamiesčio namų rūsius (Šlapelių namų-muziejaus rūsius), kur pažinsime daug kitų požeminio miesto slėpinių.\r\n\r\nEkskursijos metu lankomi šie objektai*:\r\n\r\nKatedros požemiai;  Šv. Kazimiero koplyčia; Gintaro galerijos-muziejaus rūsiai; Šlapelių namų-muziejaus rūsiai.\r\n\r\n*Lankomi objektai gali būti keičiami kitais.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2021/08/Katedros-pozemiai-TIC-1-1.jpg",
    "event_url": "https://www.vividvilnius.lt",
    "event_email": "",
    "location_name": "Pradžia nuo Katedros aikštės varpinės laiptelių",
    "location_info": "",
    "category": "Ekskursijos",
    "location_address": "Katedros a. 2",
    "location_url": ""
  },
  {
    "id": 184686,
    "link": "https://www.vilnius-events.lt/renginiai/senamiescio-labirintai-5/",
    "date": "2023-04-15 11:00",
    "all_dates": "",
    "title": "Senamiesčio labirintai",
    "content": "„SENAMIESČIO LABIRINTAI“ (rusų kalba)\r\nLabirintai... Labirintai... Mūsų Senamiestis – vienas didelis labirintas! Klaidžiodamas labirintais, kaskart nežinai, kur atsirasi, kur tave išneš srovė. Tai sprendi ne tu, tai sprendžia mūsų Nerealus miestas...\r\nPuiki galimybė tai išbandyti ekskursijoje „SENAMIESČIO LABIRINTAI“\r\nJūsų laukia nepakartojama Vilniaus kiemelių aura!\r\nSenamiesčio kiemai saugo daug paslapčių, nuo Viduramžių iki mūsų dienų.\r\nBilietus galima įsigyti: https://tickets.paysera.com/lt/event/senamiescio-labirintai-rusu-kalba\r\nRegistracija: mark@markoturas.lt, tel. +37065920741\r\nSusitikimo vieta: Vokiečių gatvės fontanas, Vilnius",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/Labirinty.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Vokiečių gatvė",
    "location_info": "",
    "category": "Ekskursijos",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 182297,
    "link": "https://www.vilnius-events.lt/renginiai/masonai-vilniuje-2/",
    "date": "2023-04-15 11:00",
    "all_dates": "",
    "title": "Masonai Vilniuje",
    "content": "Siūlau pavaikštinėti po Vilnių, surasti lietuviškųjų laisvųjų mūrininkų pėdsakų ir išgirsti intriguojančių istorijų. Istorijos bus iš pirmų lūpų! Ekskursijoje aiškinsimės šios organizacijos esmę, simbolius ir realius darbus. Masonų ložės paslaptingos, tad ir ekskursijos maršrutas paaiškės tik sudalyvavusiems (daugiausiai vaikščiosime Senamiestyje, ekskursiją baigsime netoli Šv. Onos bažnyčios). Po ekskursijos galėsite ir patys siekti taurių masoniškų tikslų. Būtina registracija el. paštu lietuvosgide@gmail.com, užsiregistravusiems pranešu ekskursijos pradžios vietą. Iki pasimatymo!\r\n\r\nGidė Asta",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/02/neuzmirstuoles-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Kalnų parkas",
    "location_info": "",
    "category": "Po atviru dangumi, Ekskursijos",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 184614,
    "link": "https://www.vilnius-events.lt/renginiai/seimu-edukacija-barbora-etc-2/",
    "date": "2023-04-15 12:00",
    "all_dates": "",
    "title": "Šeimų edukacija „Barbora etc.“",
    "content": "Kviečiame į edukaciją šeimas, skirtą Barboros Radvilaitės gyvenimo istorijai pažinti. „Barbora etc.“ – tai karalienės parašas: Lenkijos karalienė ir Lietuvos didžioji kunigaikštienė laiškus dažnai pasirašydavo itin paprastai, o ne priderančia iškilminga forma. Skaitydami šiuos susirašinėjimus su artimaisiais, aptardami mitybą, garderobą ir keliones galime pažinti kitą didikės gyvenimo pusę. Medžiagos ir kvapai, įprasti jos aplinkai, puikiai atskleidžia kasdienio gyvenimo detales. Nusprendėme juos rekonstruoti, atkartoti ir sudėti į stalčius komodos, tarsi tapusios privačiu baldu, saugančiu vaistus, kvepalus, brangenybes. Juos apžiūrėję kartu keliausime į katedrą, kurios rūsiuose, karališkajame mauzoliejuje ilsisi karalienės palaikai.\r\n\r\nEdukacijos trukmė – 1,5 val.\r\n\r\nRenginys yra Vilnius 700 programos dalis.\r\nMuziejaus veiklą finansuoja: Vilniaus arkivyskupija, Lietuvos kultūros taryba.\r\nProjekto rėmėjas: Vilniaus miesto savivaldybė.\r\n\r\nParodos plakate – S. Kuzma, Barbora Radvilaitė, Nacionalinio muziejaus Lietuvos Didžiosios Kunigaikštystės valdovų rūmų nuosavybė.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2022/12/Ekskursija_Barbora-etc.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Pradžia &#8211; Katedros aikštės varpinė",
    "location_info": "",
    "category": "Vaikams, Ekskursijos",
    "location_address": "(prie varpinės laiptų)",
    "location_url": ""
  },
  {
    "id": 184259,
    "link": "https://www.vilnius-events.lt/renginiai/kotryna-nusiima-kauke-9/",
    "date": "2023-04-15 12:00",
    "all_dates": "2023-04-15 12:00<br/>2023-04-22 12:00<br/>",
    "title": "Kotryna nusiima kaukę",
    "content": "Bažnyčia, kurios titulu yra buvusi pavadinta dabartinė Vilniaus gatvė.\r\nŠalia buvęs katalikiškas moterų vienuolynas, vienintelis Vilniuje iki galo nepamintas carizmo ir tam tikromis formomis egzistavęs netgi sovietmečiu.\r\nTai – tik mažutė dalelytė buvusios šventos Kotrynos bažnyčios ir benediktinių vienuolyno išskirtinumų.\r\nAtėjęs išgirsk audringų istorijų, tame tarpe ir apie pandemijoms bei karams nepavaldų tikinčiųjų ryžtą.\r\n\r\nReikalinga registracija elektroniniu paštu paulius.zaveckis@gmail.com arba telefonu 8 684 47169 (atsilieps gidas Paulius Zaveckis)",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/vilniusevents-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Susitikimo vieta: prie Šv. Kotrynos bažnyčios",
    "location_info": "",
    "category": "Ekskursijos",
    "location_address": "Vilniaus g. 30",
    "location_url": ""
  },
  {
    "id": 180768,
    "link": "https://www.vilnius-events.lt/renginiai/leliu-spektaklis-vaikams-kavos-malunelis-2/",
    "date": "2023-04-15 12:00",
    "all_dates": "",
    "title": "Lėlių spektaklis vaikams &#8221;Kavos malūnėlis&#8221;",
    "content": "<h3>Lėlių spektaklis vaikams „Kavos malūnėlis“</h3>\r\nPagal Konstanto Ildefonso Gałczyńskio pasaką\r\n\r\nKavos malūnėlis – pagrindinis spektaklio veikėjas – atsiduria Pamestų daiktų prieglaudoje, kurioje nepageidaujami, nublukę, klibantys daiktai geria vaistus nuo liūdesio, nes prieglaudos direktorius Raudonbarzdis laiko juos uždaręs dėžutėse bei draudžia vaikščioti gatvėmis ir verkti. Pamestų daiktų prieglaudoje Malūnėlis įsimyli sugedusią Skėtukę ir išskrenda į Mėnulį ieškoti specialios mašinos, skirtos skėčiams taisyti. Šioje šmaikščioje, keisčiausių personažų, burtažodžių kupinoje kelionėje Malūnėlis, herojiškai stengdamasis išgelbėti Skėtukę nuo liūdesio, atranda kai ką labai paprasto ir netikėto...\r\n\r\nSpektaklio įkvėpimu tapusi, lenkų dramaturgės Małgorzatos Sikorskos-Miszczuk scenai adaptuota žinomo lenkų poeto K. I. Gałczyńskio pasaka „Kavos malūnėlis“ žiūrovams žada ritmišką bei simboliais iškalbingą lėlių vaidinimą, kuriame lyriški ir žaismingi nuotykiai keis vieni kitus.\r\n\r\nĮdomu tai, jog K. I. Gałczyńskis išgarsėjęs savo absurdo miniatiūrų ir humoreskų rinkiniu „Žaliojo žąsinėlio teatras“ (Vilniaus teatre „Lėlė“ 2010 m. pagal šį kūrinį buvo sukurtas spektaklis jaunimui), „Kavos malūnėlį“ sukūrė gyvendamas Malūnų gatvėje, Vilniuje.\r\n\r\n„Suprantu, kad migduku galima gimti, bet ar reikia juo būti visą gyvenimą?“ – klausia vienas mūsų istorijos herojus. Ir man atrodo, kad šis klausimas geriausiai atspindi spektaklio prasmę. Mes nesiekiame rasti atsakymų – mieliau užduodame klausimus. Mano galva, „Kavos malūnėlis“ – tai spektaklis apie savo potencialo atskleidimą. O tuo pat metu ir apie tai, kokių gydomųjų galių turi apkabinimai, kurių mums šiomis dienomis taip trūksta.” – pasakoja „Lėlės“ teatre nebe pirmą kartą kurianti (spektaklis „Raudonoji knyga“) lenkų režisierė Ewa Piotrowska.\r\n\r\nKontaktas: Tel.: 8 5 261 40 17; El. p.: info@teatraslele.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/KavosMalunelis-136-1-scaled-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus „Lėlės“ teatras",
    "location_info": "",
    "category": "Spektakliai, Vaikams",
    "location_address": "Arklių g. 5",
    "location_url": "http://www.teatraslele.lt"
  },
  {
    "id": 184644,
    "link": "https://www.vilnius-events.lt/renginiai/seimu-edukacija-biblijos-teatras-velykines-istorijos-senuosiuose-paveiksluose-2/",
    "date": "2023-04-15 12:00",
    "all_dates": "",
    "title": "Šeimų edukacija „Biblijos teatras: velykinės istorijos senuosiuose paveiksluose“",
    "content": "Ar esate matę bažnyčią, papuoštą kaip teatro sceną? Anksčiau prieš šv. Velykas čia galėjai pamatyti ir Samsoną, kovojantį su liūtu, ir tris dienas žuvies pilve tūnojusį pranašą Joną, ir Kristaus kapo sargybinius. Ne visi tokie paveikslai išliko iš senųjų laikų. Tai, ko nebėra, sukurkime kartu! Apsilankę parodoje „Theatrum biblicum“, panagrinėję išlikusius paveikslus, kursime savą popierinį teatrą ir įamžinsime jame netikėčiausias Biblijos istorijas.\r\n\r\nTrukmė – 1,5 val.\r\n\r\nRenginys yra Vilnius 700 programos dalis.\r\nMuziejaus veiklą finansuoja: Vilniaus arkivyskupija, Lietuvos kultūros taryba.\r\nBūtina registruotis iš anksto <a href=\"https://bpmuziejus.lt/lt/pagrindinis-meniu/renginiai.html,seimu-edukacija-biblijos-teatras-velykines-istorijos-senuosiuose-paveiksluose\">ČIA</a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/kariai-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Bažnytinio paveldo muziejus",
    "location_info": "<p>Valstybinių švenčių dienomis muziejus nedirba</p>",
    "category": "Vaikams, Kiti",
    "location_address": "Šv. Mykolo g. 9",
    "location_url": "http://www.bpmuziejus.lt"
  },
  {
    "id": 181349,
    "link": "https://www.vilnius-events.lt/renginiai/ilgoji-pertrauka-keistuoliu-teatras-2/",
    "date": "2023-04-15 12:00",
    "all_dates": "",
    "title": "Ilgoji pertrauka | Keistuolių teatras",
    "content": "Dviem auksiniais scenos kryžiais apdovanota režisierė Olga Lapina ir Keistuolių teatro aktoriai, pasitelkę Milošo Macoureko pasakas bei apsakymus, praveria duris į ypatingai trapų ir jautrų pasaulį – pirmuosius žingsnius mokykloje žengiančio vaiko išgyvenimus naujoje ir nepažįstamoje sistemoje. Čekų rašytojas, legendinių pasakų apie Bonifacijaus atostogas ir begemotą, bijantį skiepų, autorius M. Macourekas savo kūriniais liudija, kad vaiko privilegija ir pagrindinė teisė yra jo fantazija – natūralioji kūrybinė jėga. Rašytojo tekstai iš vaikų literatūros išsiskiria netradiciniais įvaizdžiais, žaismingai absurdiškais istorijos sprendimais bei suaugusiojo akiai netikėtais personažais, kurie su spektakliu „Ilgoji pertrauka“ persikelia į Keistuolių teatro sceną.\r\n\r\nScenoje atgimstančius kūrinius sieja viena tema - atėjimas į pirmąją klasę. Kas atsitinka mažam žmogui, išgyvenančiam aplinkos bei sistemos, pagal kurią jis gyveno iki šiol, apsivertimą aukštyn kojomis? Spektaklio kūrybinė komanda ieško atsakymo į šį klausimą pasitelkdami abstrakčią erdvę, estetiką ir ieškodami vaikiškos logikos, kalbos bei santykių jungties. „Vertingiausias dalykas, kurį atradome M. Macoureko kūryboje – didžiulė pagarba vaiko vidiniam pasauliui. Spektaklis primena žiūrovams, jog buvimas mokyklos sistemoje negali sunaikinti žingeidžios, išradingos, fantazija paremtos mažojo žmogaus prigimties, – o juk atėjęs į mokyklą vaikas išgyvena nuolatinį konfliktą tarp to, kaip jis turėtų atrodyti bei elgtis ir to, kaip pats save įsivaizduoja. Su „Ilgąja pertrauka“ tęsiame M. Macoureko tradiciją ir atliekame savotišką teatrinį vaiko vidinio pasaulio tyrimą“, – mintimis dalinosi režisierė O. Lapina.\r\n\r\n„Ilgoji pertrauka“ – spektaklis ne tik mokyklinukams, tiems, apie kuriuos kalbama scenoje; tai kūrinys visiems jų aplinkoje esantiems žmonėms, tėvams bei mokytojams, atskleidžiantis vaizdingą, vaiko akyse bei mintyse nuolat besimainantį pasaulį - visiškai kitokį, nei regime suaugusiojo žvilgsniu. Tuo pačiu tai ir spektaklis kiekvienam, kažkada patyrusiam, ką reiškia iš savo saugaus ir šiek tiek pasakiško pasaulio žengti į didelį, kitonišką ir bauginantį mokyklos gyvenimą.\r\n\r\nRežisierė – Olga Lapina\r\n\r\nScenoje – Judita Urnikytė, Jonas Šarkus, Benita Vasauskaitė, Danas Kamarauskas\r\n\r\nBalsas už kadro – Vladas Bagdonas\r\n\r\nScenografija ir kostiumai – Renata Valčik\r\n\r\nKompozitorius – Jokūbas Tulaba\r\n\r\nŠviesų dailininkas – Darius Malinauskas\r\n\r\nRekomenduojama vaikams nuo 7 metų\r\n\r\nPremjera – 2016 m. lapkričio 20 d.\r\n\r\nPastatymo remėjas – Lietuvos Kultūros Taryba\r\n\r\nSpektaklis yra Vilnius 700 programos dalis.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/Ilgoji-pertrauka-23-photo-D.Matvejev-1-1.jpg-2-1.jpg",
    "event_url": "https://bilietai.keistuoliai.lt/event/28?fbclid=IwAR0ho3vAjpnwe4XCOBk3wmwwus3JX--3leWGltDs0mSkbEIRwXzhS0jccPU",
    "event_email": "",
    "location_name": "Keistuolių teatras",
    "location_info": "",
    "category": "Vilnius 700, Spektakliai, Vaikams",
    "location_address": "Laisvės pr. 60",
    "location_url": "http://www.keistuoliai.lt"
  },
  {
    "id": 183285,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursija-gedimino-pilies-boksto-muziejuje-gedimino-laiskai-tada-ir-dabar/",
    "date": "2023-04-15 12:00",
    "all_dates": "2023-04-15 12:00<br/>2023-04-21 17:00<br/>2023-04-29 12:00<br/>2023-05-06 12:00<br/>2023-05-20 12:00<br/>",
    "title": "Ekskursija Gedimino pilies bokšto muziejuje „Gedimino laiškai: tada ir dabar“",
    "content": "Kviečiame į unikalią kelionę laiku Gedimino pilies bokšto muziejuje. Kelionę pradėsime nuo itin svarbaus ir aktualaus dokumento – Gedimino laiško nuorašo, kuriam jau 700 metų! Sužinosite daug įdomybių kodėl, kam ir kaip buvo rašomi laiškai anuomet bei kuo unikalus šio laiško nuorašas mums. Žinoma, susipažinsite, kokios pilys kadaise stovėjo Vilniuje. Taip pat pamatysite, kaip keitėsi pilių teritorija per įvairius laikotarpius. Tikimės, jog ši kelionė jums paliks neišdildomų įspūdžių! Iki susitikimo!\r\n\r\n&nbsp;\r\n\r\n<strong>Balandžio 7 d. (penktadienį) 17 val.</strong>\r\n\r\n<strong>Balandžio 15 d. (šeštadienį) 12 val.</strong>\r\n\r\n<strong>Balandžio 21 d. (penktadienį) 17 val.</strong>\r\n\r\n<strong>Balandžio 29 d. (šeštadienį) 12 val.</strong>\r\n\r\n<strong>Gegužės 6 d. (šeštadienį) 12 val.</strong>\r\n\r\n<strong>Gegužės  20 d. (šeštadienį) 12 val.</strong>\r\n\r\nLankytojo bilietas. Registracija nereikalinga.\r\n\r\nDaugiau informacijos rasite <a href=\"https://lnm.lt/renginiai/ekskursija-gedimino-pilies-boksto-muziejuje-gedimino-laiskai-tada-ir-dabar/\">čia</a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/ekskursija-gedimino-laiskai-tada-ir-dabar-vilniue-events.jpg",
    "event_url": "https://bilietai.lnm.lt/",
    "event_email": "pilis@lnm.lt",
    "location_name": "Gedimino pilis",
    "location_info": "",
    "category": "Vaikams, Ekskursijos, Kiti",
    "location_address": "Arsenalo g. 5",
    "location_url": "http://www.lnm.lt"
  },
  {
    "id": 184874,
    "link": "https://www.vilnius-events.lt/renginiai/seimu-sestadienis-sesi-elementai/",
    "date": "2023-04-15 12:00",
    "all_dates": "",
    "title": "Šeimų šeštadienis. Šeši elementai",
    "content": "Ar norėtumėte pasinerti į kūrybinį spektaklio procesą? Ar žinote, kokie esminiai elementai būtini spektaklio gimimui? O kokia yra teatro meno prigimtis? Edukacinis užsiėmimas „Šeši elementai“ supažindins su pagrindinėmis, teatre bendradarbiaujančiomis meno sritimis, suteiks galimybę patiems sukurti ir atlikti trumpas scenas. Sužinosite, ką gi veikia režisierius, susipažinsite su specifiniais, aktorių naudojamais susikaupimo scenai žaidimais, kursite muzikinį takelį ir kostiumus aktoriams! Trumpam tapkite nedidele šeimos teatro trupe ir sukurkite unikalų, visus šeimos narius sujungiantį vaidinimą!\r\n\r\nRegistracijos forma <a href=\"https://bit.ly/3Go1kHU\">ČIA</a>\r\n\r\nInformacija ir registracija pirmadieniais-penktadieniais nuo 9 iki 17 val.: tel. +370 616 711 33 arba el. paštu edukacija.ltmkm@gmail.com",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/LTMKM-sestadienis_Vilnius.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Lietuvos teatro, muzikos ir kino muziejus",
    "location_info": "<p>Valstybinių švenčių dienomis muziejus nedirba</p>",
    "category": "Vaikams",
    "location_address": "Vilniaus g. 41",
    "location_url": "http://www.ltmkm.lt"
  },
  {
    "id": 184355,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursija-kas-kure-vilniu-miesto-ir-jo-zmoniu-istorijos-3/",
    "date": "2023-04-15 12:30",
    "all_dates": "2023-04-15 12:30<br/>2023-04-22 14:30<br/>",
    "title": "Ekskursija „Kas kūrė Vilnių? Miesto ir jo žmonių istorijos“",
    "content": "Keliaudami laiku per 700 metų Vilniaus miesto istoriją, turėsite galimybę susipažinti su įvairių epochų asmenybėmis, kurios čia gyvendamos, dirbdamos ir leisdamos laisvalaikį kūrė ne tik savąjį santykį su Vilniumi, bet ir patį miestą.\r\n\r\nRemiantis įvairių tautų, profesijų ir konfesijų gyventojų istorijomis, mėginsime pamatyti daugiakultūrio ir įvairialypio istorinio Vilniaus paveikslą. Ekskursijos metu turėsite progą geriau pažinti Vilniaus kasdienybės istoriją: sužinosite, kur po sekmadienio mišių skubėdavo tarpukario vilniečiai, kur XIX a. Vilniuje buvo galima įsigyti paryžietiškų pirštinaičių ir kvepalų, kiek uždirbdavo miesto budelis ir daug kitų įdomių pasakojimų iš Vilniaus.\r\n\r\nVietų skaičius ribotas, todėl bilietus rekomenduojame įsigyti iš anksto Istorijų namų kasoje arba <a href=\"https://bilietai-ke.lnm.lt/\">čia.</a>\r\n\r\nJeigu norėtumėte užsisakyti ekskursiją grupei, rašykite el. paštu greta.gaidelyte@lnm.lt. Esant skubiems klausimams, galite skambinti tel. nr. +370 678 58025.\r\n\r\nDaugiau apie parodą „Aš esu vilnietis“ galite sužinoti <a href=\"https://lnm.lt/renginiai/paroda-as-esu-vilnietis\">lnm.lt</a> skiltyje Parodos ir renginiai.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/ekskursijos-paroda-as-esu-vilnietis-istoriju-namai-vilnius-events.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Istorijų namai",
    "location_info": "",
    "category": "Vilnius 700, Parodos, Ekskursijos",
    "location_address": "T. Kosciuškos g. 3",
    "location_url": "https://lnm.lt/muziejai/istoriju-namai/"
  },
  {
    "id": 183281,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursija-su-gidu-po-paroda-1-000-000-zingsniu-gintaro-kelias-nuo-romos-iki-baltijos-3/",
    "date": "2023-04-15 13:00",
    "all_dates": "2023-04-15 13:00<br/>2023-04-22 16:00<br/>",
    "title": "Ekskursija su gidu po parodą „1 000 000 žingsnių: Gintaro kelias nuo Romos iki Baltijos“",
    "content": "Leiskitės į kelionę po Romos imperijos klestėjimo laikus ir sužinokite, kaip Europa „atrado“ aisčius! Keliaudami Gintaro keliu pamatysite ir išgirsite, kaip anuomet buvo prekiaujama, keliaujama, ką žmonės valgė, kaip rengėsi, puošėsi, ginklavosi, kuo romėnai ir baltai buvo panašūs ir kuo skyrėsi, kaip ir kokią įtaką darė vieni kitiems, dažnai netgi nesusitikdami „akis į akį“.\r\n\r\n<strong>Kovo 18 d. (šeštadienį) 15 val.</strong>\r\n\r\n<strong>Kovo 22 d. (trečiadienį) 17.30 val.</strong>\r\n\r\n<strong>Kovo 25 d. (šeštadienį) 12 val.</strong>\r\n\r\n<strong>Balandžio 15 d. (šeštadienį) 13 val.</strong>\r\n\r\n<strong>Balandžio 22 d. (šeštadienį) 16 val.</strong>\r\n\r\nTolimesnės ekskursijų datos bus skelbiamos vėliau.\r\n\r\n<strong>Kaina: Lankytojo bilietas + 2 Eur</strong>\r\n\r\n&nbsp;\r\n\r\nJeigu norėtumėte užsisakyti ekskursiją grupei, rašykite el. paštu arba skambinkite telefonu +370 (5) 239 45 35.\r\n\r\nDaugiau apie parodą galite sužinoti lnm.lt skiltyje Parodos ir renginiai.\r\n\r\nDaugiau informacijos rastie <a href=\"https://lnm.lt/renginiai/ekskursija-su-gidu-po-paroda-1-000-000-zingsniu-gintaro-kelias-nuo-romos-iki-baltijos/\">čia</a>\r\n\r\n<strong>Vietų skaičius ribotas, todėl bilietus rekomenduojame įsigyti iš anksto. Bilietus rasite <a href=\"https://bilietai-ke.lnm.lt/lit/events/79\">čia</a></strong>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/ekskursija-gintaro-kelias-vilnius-events.jpg",
    "event_url": "",
    "event_email": "istoriju.namai@lnm.lt",
    "location_name": "Istorijų namai",
    "location_info": "",
    "category": "Parodos, Ekskursijos, Kiti",
    "location_address": "T. Kosciuškos g. 3",
    "location_url": "https://lnm.lt/muziejai/istoriju-namai/"
  },
  {
    "id": 184025,
    "link": "https://www.vilnius-events.lt/renginiai/edukacija-parodoje-1923-iuju-metu-klaipeda-ir-lietuva-istorija-politika-diplomatija-2/",
    "date": "2023-04-15 13:00",
    "all_dates": "2023-04-15 13:00<br/>2023-04-27 16:30<br/>",
    "title": "Edukacija parodoje „1923-iųjų metų Klaipėda ir Lietuva: istorija, politika, diplomatija“",
    "content": "Klaipėdos krašto prijungimas prie Lietuvos – vienas reikšmingiausių įvykių XX a. Lietuvos istorijoje, turėjęs didelę reikšmę ekonominei, kultūrinei ir politinei raidai. Šis laikotarpis dažnam vis dar mažai žinomas, o juk 1923 metais jauna Lietuvos Respublika įrodė, kad gali sėkmingai ginti savo interesus: Lietuva atsigręžė į Vakarus ir tapo jūrine valstybe. Edukaciniame užsiėmime, pasitelkę interaktyvų žaidimą, gvildensime šią temą, o atsakymų ieškosime naujausioje parodoje, atkeliavusioje tiesiai iš Mažosios Lietuvos širdies.\r\n\r\nRekomenduojama suaugusiesiems ir vyresnio mokyklinio amžiaus moksleiviams.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/03/paroda-klaipeda-ir-lietuva-naujasis-arsenalas-mazosios-lietuvos-muziejus-atidarymas-2-scaled-1-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Naujasis arsenalas",
    "location_info": "<p>Muziejus nedirba valstybinių švenčių dienomis.<br />\nDienomis prieš valstybines šventes dirba valanda trumpiau nei įprasta.</p>",
    "category": "Vaikams, Kiti",
    "location_address": "Arsenalo g. 1",
    "location_url": "http://www.lnm.lt"
  },
  {
    "id": 184762,
    "link": "https://www.vilnius-events.lt/renginiai/tarp-kodu-ir-klodu-pasivaiksciojimas-etnografijos-saugykloje-7/",
    "date": "2023-04-15 13:00",
    "all_dates": "2023-04-15 13:00<br/>2023-04-15 16:00<br/>2023-04-18 13:00<br/>2023-04-18 16:00<br/>2023-04-19 13:00<br/>2023-04-19 18:00<br/>2023-04-20 13:00<br/>2023-04-20 16:00<br/>2023-04-21 13:00<br/>2023-04-21 16:00<br/>2023-04-29 13:00<br/>2023-04-29 16:00<br/>",
    "title": "Tarp kodų ir klodų: pasivaikščiojimas etnografijos saugykloje",
    "content": "Aštuoniose salėse saugomi tūkstančiai įvairiausių etnografinių artefaktų, kurie ne visi šiandien mums bepažįstami. Koks lietuvio genas juose užkoduotas? Kokius etninės kultūros klodus išlaikėme, įamžinome, o ką per laiką primiršome? Ar galime ką nors naujo atrasti praeityje?\r\n\r\nKviečiame į pasivaikščiojimą po Lietuvos nacionalinio muziejaus etnografijos eksponatų saugyklą-ekspoziciją. Tai vienintelė visoje šalyje vieta, kurioje galima išvysti gausią ir įvairialypę kolekciją, menančią prieš 200 ir daugiau metų gyvenusių lietuvių tapatybę, įamžintą architektūroje, namų interjere, buityje, amatuose ir versluose.\r\n\r\nEkskursija rekomenduojama asmenims nuo 12 metų.\r\n\r\nVietų skaičius ribotas, todėl bilietus rekomenduojame įsigyti iš anksto <a href=\"https://bilietai-ke.lnm.lt/lit/events/53\">ČIA</a>\r\n\r\nJeigu norėtumėte užsisakyti ekskursiją grupei, rašykite el. paštu neringa.andriuskeviciute@lnm.lt arba skambinkite telefonu (8-5) 239 4574.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/Tarp-kodu-ir-klodu-pasivaiksciojimas-etnografijos-saugykloje-750-600-piks.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Istorijų namai",
    "location_info": "",
    "category": "Ekskursijos",
    "location_address": "T. Kosciuškos g. 3",
    "location_url": "https://lnm.lt/muziejai/istoriju-namai/"
  },
  {
    "id": 184618,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursija-ekstremalus-vilniaus-katedros-pozemiu-marsrutas-4/",
    "date": "2023-04-15 14:00",
    "all_dates": "2023-04-15 14:00<br/>2023-04-22 14:00<br/>2023-04-29 14:00<br/>",
    "title": "Ekskursija „Ekstremalus Vilniaus katedros požemių maršrutas“",
    "content": "Kviečiame patirti ekstremalius pojūčius ekskursijoje ilgajame Vilniaus katedros požemių maršrute. Tai viena įdomiausių, istoriškai ir kultūriškai vertingiausių Lietuvos erdvių, liudijančių valstybės istoriją nuo XIV a. iki šių dienų, kasmet pritraukianti dešimtis tūkstančių lankytojų.\r\nŠiaurinė katedros požemių dalis leidžia lankytojams pamatyti ir išgirsti apie ilgus metus tiesiogine to žodžio prasme buvusias neprieinamas, užmūrytas ar užtvertas erdves.\r\nEkskursijos dalyviai galės apžiūrėti vienų seniausių Lietuvoje mūrų, XIII–XIV a. bokšto ir laiptų liekanas, istoriškai neįkainojamus Jogailos ir Vytauto katedros mūrus, skirtingas laidojimo tradicijas menančias XVI–XIX a. kriptas ir mauzoliejų, XVII–XVIII a. katedros rekonstrukcijas liudijančias sienas, gotikines plytas, keramikos fragmentus, XX a. 4 deš. gelžbetoninius įtvirtinimus, XVIII a. drenažinę sistemą, 8–9 deš. geologinių tyrimų mėginius ir kitas vertybes, išsidėsčiusias nemažame, 120 kv. m plote po Vilniaus katedra.\r\nNorintiems dalyvauti patariama įsivertinti savo fizinius gebėjimus: siekiant kuo labiau išsaugoti erdvės autentiškumą, čia palikti originalūs praėjimai, kai kuriose vietose susiaurėjantys iki 40 cm pločio. Aukščiausias laiptelis, kurį reikia įveikti norint praeiti visą maršrutą, – 42 cm aukščio.\r\n\r\nEkskursijos trukmė – 1 val. 30 min. Būtina išankstinė registracija <a href=\"https://bpmuziejus.lt/\">ČIA</a>\r\n\r\nRenginys yra Vilnius 700 programos dalis.\r\nMuziejaus veiklą finansuoja: Vilniaus arkivyskupija, Lietuvos kultūros taryba.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/1589544039_0_03_Pozemiai_003_Fot._Arunas_Baltenas.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Startas ir finišas prie Vilniaus Katedros varpinės",
    "location_info": "",
    "category": "Vilnius 700, Ekskursijos",
    "location_address": "",
    "location_url": ""
  },
  {
    "id": 184634,
    "link": "https://www.vilnius-events.lt/renginiai/ekskursija-vilniaus-katedros-lobynas-6/",
    "date": "2023-04-15 14:00",
    "all_dates": "2023-04-15 14:00<br/>2023-04-22 14:00<br/>2023-04-29 14:00<br/>",
    "title": "Ekskursija „Vilniaus katedros lobynas“",
    "content": "Kviečiame apžiūrėti nuostabias Vilniaus katedros lobyno vertybes. Vilniaus katedros lobynas – pats seniausias ir gausiausias iš visų Lietuvos Didžiosios Kunigaikštystės bažnyčiose saugotų lobynų. Valdovai, didikai, vyskupai vos įsteigtai katedrai dovanojo prabangius liturginius reikmenis: kryžius, taures, relikvijorius, monstrancijas. Šie sakralaus meno kūriniai – išraiškingi maldingumo tradicijos liudytojai ir auksakalystės šedevrai. Neramiais krašto istorijos laikotarpiais lobynas būdavo slepiamas, o paskutinį kartą slėptuvėje atsidūrė Antrojo pasaulinio karo išvakarėse ir liko ten iki 1985 metų – išgirsite ir paslaptingą jo atradimo istoriją.\r\nEkskursijos metu taip pat pasivaikščiosite po Šv. arkangelo Mykolo bažnyčią ir buvusį bernardinių vienuolyną – įspūdingą Renesanso laikų ansamblį, pastatytą LDK kanclerio Leono Sapiegos (1557–1633) iniciatyva ir tapusį fundatoriaus šeimos mauzoliejumi.\r\n\r\nEkskursijos trukmė – 1 val.\r\n\r\nRenginys yra Vilnius 700 programos dalis.\r\nMuziejaus veiklą finansuoja: Vilniaus arkivyskupija, Lietuvos kultūros taryba.\r\nBūtina išankstinė registracija.\r\nKontaktas: tel. + 370 5 269 7800, el. p. edukacija@bpmuziejus.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/1650877615_0_Ekskursija_Lobynai-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Bažnytinio paveldo muziejus",
    "location_info": "<p>Valstybinių švenčių dienomis muziejus nedirba</p>",
    "category": "Vilnius 700, Ekskursijos",
    "location_address": "Šv. Mykolo g. 9",
    "location_url": "http://www.bpmuziejus.lt"
  },
  {
    "id": 182239,
    "link": "https://www.vilnius-events.lt/renginiai/pasaka-vaikams-aukso-obelele-vyno-sulinelis-5/",
    "date": "2023-04-15 14:00",
    "all_dates": "",
    "title": "Pasaka vaikams &#8221;Aukso obelėlė, vyno šulinėlis&#8221;",
    "content": "„Aukso obelėlė, vyno šulinėlis“ - viena iš gražiausių ir populiariausių lietuviškų pasakų. Tai stebuklinga istorija apie Pamotės engiamą Našlaitę. Kaip ir kiekvienoje tokio tipo pasakoje, čia apstu blogio keliamų kliūčių: nedorėlė ragana kartu su savo dukromis kankina mergelę skirdama neįveikiamas užduotis, tačiau gėris, padedamas stebuklingų jėgų, galiausiai laimi ir Našlaitę pasakos pabaigoje išlaisvina bei veda jaunas Karalius.\r\n\r\nSpektaklio kūrėjams šiame pastatyme imponuoja galimybė panaudoti vaizdo teatro formas, kurios labiau priklauso kino menui, nei teatrui. Nors pasakoje nemažai liaudies dainų ir eiliavimo, spektaklyje pasakojimas kuriamas labiau vaizdais. Žiūrovai regės tokias įvairias dar nuo Antikinės Graikijos laikų populiarias vaizdinio teatro priemones kaip panoramas, mirioramas, diaoramas, taumatropą, laterna magica, mirioramines kortas, taip pat – šešėlių teatrą.\r\n\r\n„Pirmą kartą šią pasaką stačiau scenos mylėtojų draugijoje „Teatrinės iniciatyvos“ (premjera 1997 12 18). Tada kūriau ir scenografiją. Anuomet šį monospektaklį marionetėmis vaidinęs Vilniaus „Senamiesčio teatro“ aktorius Dainius Vengelis, baigdamas 2009 m. Lietuvos muzikos ir teatro akademijos magistrantūrą, pagal tą spektaklį kūrė savo diplominį vaidinimą (scenografė Neringa Keršulytė). Grįždamas prie šios pasakos „Lėlėje“ aš rėmiausi prieš keletą šimtmečių lėlininkų naudota reginių ir optinių metamorfozių kolekcija (mechaninis teatras, diorama, miriorama, moire, Jokūbo kopėčios, Laterna magica ir kt.). Šios reginio formos šiandien priskiriamos kinematografijos kilmės istorijai.“ (rež. R. Driežis)\r\n\r\nScenarijaus autorius ir režisierius: Rimas Driežis\r\nDailininkas: Marius Jonutis\r\nMuziką sukūrė ir parinko: Faustas Latėnas\r\nVideo animacijos autorius: Algimantas Driežis\r\n\r\nVaidina:\r\nElvyra PIŠKINAITĖ\r\nLijana MUŠTAŠVILI\r\n\r\nTrukmė: 45 min.\r\nPremjera - 2011 m. kovo 26 d.\r\n\r\n<strong>Kontaktas:</strong> Tel.: 8 5 261 40 17; El. p.: info@teatraslele.lt",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/02/Auksoobel.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Vilniaus „Lėlės“ teatras",
    "location_info": "",
    "category": "Vaikams",
    "location_address": "Arklių g. 5",
    "location_url": "http://www.teatraslele.lt"
  },
  {
    "id": 184682,
    "link": "https://www.vilnius-events.lt/renginiai/nerealios-vilniaus-kiemeliu-istorijos-6/",
    "date": "2023-04-15 14:00",
    "all_dates": "2023-04-15 14:00<br/>2023-04-16 11:00<br/>2023-04-23 11:00<br/>",
    "title": "Nerealios Vilniaus kiemelių istorijos",
    "content": "Nerealus Vilniaus senamiesčio kiemeliai... (rusų kalba)\r\n\r\nPanašus ir skirtingi...  Kiekvienas kiemelis – tai atskiras pasaulis, su savo gyventojais, skulptūromis ir savo neįtikėtinomis istorijomis...\r\nDaugiau šių nerealių istorijų sužinosite, apsilankę NEREALAUS VILNIAUS ekskursijoje „NEREALIOS VILNIAUS KIEMELIŲ ISTORIJOS...!“\r\nNepakartojama Vilniaus kiemelių aura laukia Jūsų! Senamiesčio kiemai saugo daug paslapčių, nuo viduramžių iki mūsų dienų.\r\nNetgi vietiniai gyventojai stebisi išgirdę savo namų istorijas, kurios dažnai buna įdomesnės nei visiems žinomos Vilniaus legendos...\r\n\r\nRegistracija: mark@markoturas.lt, tel. +37065920741",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/KIEMAI-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Aušros Vartai",
    "location_info": "",
    "category": "Po atviru dangumi, Ekskursijos",
    "location_address": "Aušros Vartų g. 14",
    "location_url": "http://www.ausrosvartai.lt"
  },
  {
    "id": 181351,
    "link": "https://www.vilnius-events.lt/renginiai/detektyvas-d-lapinas-keistuoliu-teatras/",
    "date": "2023-04-15 15:00",
    "all_dates": "",
    "title": "Detektyvas D. Lapinas | Keistuolių teatras",
    "content": "Detektyvinė pasaka\r\n\r\nžmonėms nuo 6 metų\r\n\r\nUdrių miške gyvenimas teka sava vaga. Čia, kaip ir bet kuriame kitame miške, žvėreliai kiekvieną dieną mokosi ir dirba, išgyvena savus džiaugsmus ir rūpesčius. Tik įprastą miško ramybę staiga nutraukia paslaptingas skambutis – dingo naujokė Meškutė. Šios bylos imasi detektyvas Lapinas. Atidžiai sekant įkalčių pėdsakais, apklausinėjant miško gyventojus, Lapinui po truputį ima aiškėti paslaptingos istorijos kontūrai. Kokius įkalčius detektyvui pavyko rasti? Ką Lapinas sužinos, apklausęs miško žvėrelius? Ir svarbiausia – ar jam pavyks išpinti šią mįslių kupiną istoriją ir rasti Meškutę? O mes vieną užuominą paliekame čia – ši istorija visus žiūrėjusius išmokys, kad patekus į bėdą – visada yra išeitis...\r\n\r\nRežisierius ir kompozitorius – Aidas Giniotis\r\n\r\nVaidina: Eimantas Bareikis, Marija Korenkaitė, Justina Smieliauskaitė, Benita Vasauskaitė, Danas Kamarauskas, Diana Kamarauskaitė, Jonas Šarkus, Aurimas Bačinskas, Matas Pranskevičius\r\n\r\nScenografė ir kostiumų dalininkė – Ramunė Skrebūnaitė\r\n\r\nPremjera 2022 12 03",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/02/C_LauraVanseviciene-9-scaled-1.jpg",
    "event_url": "",
    "event_email": "",
    "location_name": "Keistuolių teatras",
    "location_info": "",
    "category": "Spektakliai, Vaikams",
    "location_address": "Laisvės pr. 60",
    "location_url": "http://www.keistuoliai.lt"
  },
  {
    "id": 180335,
    "link": "https://www.vilnius-events.lt/renginiai/detektyvo-d-lapino-byla-keistuoliu-teatras/",
    "date": "2023-04-15 15:00",
    "all_dates": "2023-04-15 15:00<br/>2023-06-03 15:00<br/>",
    "title": "Detektyvo D. Lapino byla | Keistuolių teatras",
    "content": "Udrių miške gyvenimas teka sava vaga. Čia, kaip ir bet kuriame kitame miške, žvėreliai kiekvieną dieną mokosi ir dirba, išgyvena savus džiaugsmus ir rūpesčius. Tik įprastą miško ramybę staiga nutraukia paslaptingas skambutis – dingo naujokė Meškutė. Šios bylos imasi detektyvas Lapinas. Atidžiai sekant įkalčių pėdsakais, apklausinėjant miško gyventojus, Lapinui po truputį ima aiškėti paslaptingos istorijos kontūrai. Kokius įkalčius detektyvui pavyko rasti? Ką Lapinas sužinos, apklausęs miško žvėrelius? Ir svarbiausia – ar jam pavyks išpinti šią mįslių kupiną istoriją ir rasti Meškutę? O mes vieną užuominą paliekame čia – ši istorija visus žiūrėjusius išmokys, kad patekus į bėdą – visada yra išeitis...\r\n\r\nRežisierius ir kompozitorius – Aidas Giniotis\r\n\r\nVaidina: Eimantas Bareikis, Marija Korenkaitė, Justina Smieliauskaitė, Benita Vasauskaitė, Danas Kamarauskas, Diana Kamarauskaitė, Jonas Šarkus, Aurimas Bačinskas, Matas Pranskevičius\r\n\r\nScenografė ir kostiumų dalininkė – Ramunė Skrebūnaitė.\r\n\r\nDetektyvinė pasaka žmonėms nuo 6 metų\r\n\r\nSpektaklis yra Vilnius 700 programos dalis.",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/01/324333738_654646796346697_2962828693151846169_n.png",
    "event_url": "https://bilietai.keistuoliai.lt/event/101?fbclid=IwAR1d0XxLg67X2HrsoBn-sH6dKxocb1HovT24VVz7HSusBod3Spq8NffK9Z4",
    "event_email": "",
    "location_name": "Keistuolių teatras",
    "location_info": "",
    "category": "Vilnius 700, Spektakliai, Vaikams",
    "location_address": "Laisvės pr. 60",
    "location_url": "http://www.keistuoliai.lt"
  },
  {
    "id": 184764,
    "link": "https://www.vilnius-events.lt/renginiai/patyrimines-dirbtuves-herojes-kolekcija/",
    "date": "2023-04-15 15:15",
    "all_dates": "",
    "title": "Patyriminės dirbtuvės “Herojės kolekcija”",
    "content": "Dar 2008 m. birželį Phyl Terry, „Reading Odyssey“ ir „Collaborative Gain“ įkūrėjas, surengė eksperimentą. Norėta sužinoti, kas nutiktų, jei muziejų ir galerijų lankytojai pakeistų požiūrį į meną. Užuot perbėgę šimtus meno kūrinių per standartines 8 sekundes, žmonės buvo kviečiami lėtai žiūrėti tik į keletą kūrinių. Eksperimentą pakartojo 2009 m. vasarą, šis buvo toks sėkmingas, jog spalį, Phyl surengė trečiąjį testą su draugais iš viso pasaulio, kurie organizavo slaptą lėtą žiūrėjimą 16 muziejų ir galerijų JAV, Kanadoje ir Europoje. Per kelerius metus renginys, įveiktęs muziejų pasipriešinimą, įsitvirtino. O šiandien muziejai oficialiai įsitraukia į savo metines edukacines programas. Be to, kai kuriuose muziejuose vyksta reguliarios savaitės ar mėnesio lėtosios peržiūros sesijos.\r\n\r\n“Herojės kolekcija” - lėtos 88 minutės kultūrinėje kelionėje mažoje grupėje (iki 13 asmenų):\r\n\r\n- mokysimės lėto dialogo apie meną\r\n- ištestuosime kaip atmintis veikia kūrybiškumą\r\n- rašysime (fiksuosime)\r\n- susipažinsime su fotografijų kolekcijos “Herojės kelionė” sudarymo ir vidinio augimo praktikos strategija\r\n- reflektuosime patyrimą\r\n\r\nDirbtuves ves ir erdvę saugos kūrybiškumo fasilitatorė Gerda Šeirė.\r\n\r\nTinka smalsiems ir atviriems - tai esminės kūrybingos asmenybės savybės. Naudingiausios racionaliems bei gebantiems identifikuoti, jog trūksta motyvacijos atsiverti kūrybiškumui bei pradėti save visapusiškai lavinti.\r\n\r\nFotografijos kultūra susideda ir iš mūsų pačių kultūrinės atminties bei gyvento laikmečio liudijimų. Žvilgsnis, pasikartojančiai užkliūvantis už tam tikrų siužetų, gali padėti keliauti nauju, kūrybišku savęs auginimo keliu.\r\n\r\nRekvizitai apmokėjimui ir informacija apie dirbtuvių vietą atsiunčiami tik patvirtintiems dirbtuvių dalyviams. Registracija <a href=\"https://forms.gle/hNu7FV6FNoBdebQB9\">ČIA </a>",
    "image_src": "https://www.vilnius-events.lt/wp-content/uploads/2023/04/CC7C0700-46E0-4362-8D3B-9CA28F3C7306-1.png",
    "event_url": "",
    "event_email": "",
    "location_name": "Senamiestis",
    "location_info": "",
    "category": "Kiti",
    "location_address": "",
    "location_url": ""
  }
]